import crypto from'node:crypto';
export const ROLES=['owner','admin','operator','viewer'];export class AppError extends Error{constructor(code,status=400){super(code);this.code=code;this.status=status}}const bad=(c,s=400)=>{throw new AppError(c,s)},hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex'),mac=(s,v)=>crypto.createHmac('sha256',s).update(v).digest('hex'),eq=(a,b)=>{let x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)},txt=(v,a,b,c)=>{if(typeof v!=='string'||v.trim().length<a||v.length>b)bad(c);return v.trim()};
export function createState({clock=()=>new Date().toISOString(),auditSecret='local-audit-change-me',workerSecret='local-worker-change-me'}={}){return{tenants:new Map,members:new Map,apiKeys:new Map,runs:new Map,audit:[],auditHeads:new Map,dlq:[],clock,auditSecret,workerSecret}}
export function provisionTenant(s,{slug,name,plan='free',monthlyRunLimit=100,ownerUserId}){slug=txt(slug,3,48,'invalid_tenant_slug');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))bad('invalid_tenant_slug');name=txt(name,2,100,'invalid_tenant_name');ownerUserId=txt(ownerUserId,2,100,'invalid_owner');if(!['free','starter','pro'].includes(plan))bad('invalid_plan');if(!Number.isSafeInteger(monthlyRunLimit)||monthlyRunLimit<1||monthlyRunLimit>100000)bad('invalid_run_limit');if([...s.tenants.values()].some(t=>t.slug===slug))bad('tenant_exists',409);const id=`ten_${hash(slug).slice(0,24)}`,t={id,slug,name,plan,monthlyRunLimit,usedRuns:0,status:'active',createdAt:s.clock()};s.tenants.set(id,t);s.members.set(`${id}:${ownerUserId}`,{tenantId:id,userId:ownerUserId,role:'owner'});audit(s,id,'tenant.provisioned',{slug,plan,ownerUserId},ownerUserId);return t}
export function authorize(s,{tenantId,userId,minimum='viewer'}){if(!s.tenants.has(tenantId))bad('tenant_not_found',404);if(!ROLES.includes(minimum))bad('invalid_permission');const m=s.members.get(`${tenantId}:${userId}`);if(!m)bad('membership_required',403);if(ROLES.indexOf(m.role)>ROLES.indexOf(minimum))bad('insufficient_role',403);return m}
export function addMember(s,{tenantId,actorId,userId,role}){authorize(s,{tenantId,userId:actorId,minimum:'admin'});userId=txt(userId,2,100,'invalid_user');if(!ROLES.includes(role))bad('invalid_role');const m={tenantId,userId,role};s.members.set(`${tenantId}:${userId}`,m);audit(s,tenantId,'member.upserted',{userId,role},actorId);return m}
export function issueApiKey(s,{tenantId,actorId,label,scopes=['runs:read'],ttlSeconds=3600}){authorize(s,{tenantId,userId:actorId,minimum:'admin'});label=txt(label,2,60,'invalid_key_label');const allowed=['runs:read','runs:write','members:write','keys:write'];if(!Array.isArray(scopes)||!scopes.length||scopes.some(x=>!allowed.includes(x)))bad('invalid_scopes');if(!Number.isSafeInteger(ttlSeconds)||ttlSeconds<60||ttlSeconds>31536000)bad('invalid_key_ttl');const id=`key_${crypto.randomBytes(9).toString('hex')}`,token=`mts_${crypto.randomBytes(32).toString('base64url')}`,expiresAt=new Date(Date.parse(s.clock())+ttlSeconds*1000).toISOString();s.apiKeys.set(id,{id,tenantId,actorId,label,scopes:[...new Set(scopes)],keyHash:hash(token),revoked:false,expiresAt});audit(s,tenantId,'api_key.issued',{id,label,scopes,expiresAt},actorId);return{id,token,expiresAt}}
export function authenticate(s,token,scope){if(typeof token!=='string'||!token.startsWith('mts_'))bad('invalid_api_key',401);const h=hash(token),k=[...s.apiKeys.values()].find(x=>eq(x.keyHash,h));if(!k||k.revoked||Date.parse(k.expiresAt)<=Date.parse(s.clock()))bad('invalid_api_key',401);if(scope&&!k.scopes.includes(scope))bad('insufficient_scope',403);return k}
export function revokeApiKey(s,{tenantId,actorId,keyId}){authorize(s,{tenantId,userId:actorId,minimum:'admin'});const k=s.apiKeys.get(keyId);if(!k||k.tenantId!==tenantId)bad('key_not_found',404);k.revoked=true;audit(s,tenantId,'api_key.revoked',{keyId},actorId);return{id:keyId,revoked:true}}
export function enqueueRun(s,{tenantId,workflowId,idempotencyKey,actorId}){authorize(s,{tenantId,userId:actorId,minimum:'operator'});workflowId=txt(workflowId,2,100,'invalid_workflow_id');idempotencyKey=txt(idempotencyKey,8,128,'invalid_idempotency_key');const t=s.tenants.get(tenantId);if(t.status!=='active')bad('tenant_inactive',403);const old=[...s.runs.values()].find(r=>r.tenantId===tenantId&&r.idempotencyKey===idempotencyKey);if(old)return{...old,replayed:true};if(t.usedRuns>=t.monthlyRunLimit)bad('quota_exceeded',429);const r={id:`run_${hash(`${tenantId}:${idempotencyKey}`).slice(0,20)}`,tenantId,workflowId,idempotencyKey,status:'queued',attempt:0,maxAttempts:3,createdAt:s.clock(),updatedAt:s.clock()};s.runs.set(r.id,r);t.usedRuns++;audit(s,tenantId,'run.enqueued',{runId:r.id,workflowId},actorId);return r}
export function completeRun(s,{tenantId,runId,success,errorCode,workerSecret}){if(!eq(workerSecret,s.workerSecret))bad('invalid_worker_credential',401);const r=s.runs.get(runId);if(!r||r.tenantId!==tenantId)bad('run_not_found',404);if(['succeeded','dead_lettered'].includes(r.status))bad('terminal_run',409);if(typeof success!=='boolean')bad('invalid_completion');r.attempt++;r.updatedAt=s.clock();if(success){r.status='succeeded';audit(s,tenantId,'run.succeeded',{runId},'worker');return r}errorCode=txt(errorCode,2,80,'invalid_error_code');if(r.attempt<r.maxAttempts){r.status='retry_scheduled';audit(s,tenantId,'run.retry_scheduled',{runId,attempt:r.attempt,errorCode},'worker');return r}r.status='dead_lettered';s.dlq.push({tenantId,runId,errorCode,replayAuthorized:false});audit(s,tenantId,'run.dead_lettered',{runId,errorCode},'worker');return r}
export function listTenantRuns(s,{tenantId,userId}){authorize(s,{tenantId,userId});return[...s.runs.values()].filter(r=>r.tenantId===tenantId).map(r=>({...r}))}
export function audit(s,tenantId,event,payload,actorId){const prevHash=s.auditHeads.get(tenantId)||'GENESIS',row={id:`aud_${tenantId}_${s.audit.filter(x=>x.tenantId===tenantId).length+1}`,tenantId,event,payload,actorId,timestamp:s.clock(),prevHash};row.hash=mac(s.auditSecret,JSON.stringify(row));s.audit.push(row);s.auditHeads.set(tenantId,row.hash);return row}
export function verifyAudit(s,tenantId){let p='GENESIS';for(const r of s.audit.filter(x=>x.tenantId===tenantId)){const e=mac(s.auditSecret,JSON.stringify({id:r.id,tenantId:r.tenantId,event:r.event,payload:r.payload,actorId:r.actorId,timestamp:r.timestamp,prevHash:r.prevHash}));if(r.prevHash!==p||!eq(r.hash,e))return false;p=r.hash}return true}
