import crypto from 'node:crypto';
export const ROLES=['owner','admin','operator','viewer'];
export const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
export function createState(){return {tenants:new Map(),members:new Map(),apiKeys:new Map(),runs:new Map(),audit:[],dlq:[]}}
export function tenantId(value){return `ten_${hash(value).slice(0,16)}`}
export function createTenant(state,{slug,name,plan='free',monthlyRunLimit=100}){if(!/^[a-z0-9-]{3,48}$/.test(slug))throw Error('invalid_tenant_slug');if([...state.tenants.values()].some(t=>t.slug===slug))throw Error('tenant_exists');const id=tenantId(slug);const tenant={id,slug,name,plan,monthlyRunLimit,usedRuns:0,status:'active'};state.tenants.set(id,tenant);audit(state,id,'tenant.created',{slug,plan});return tenant}
export function addMember(state,{tenantId,userId,role}){if(!state.tenants.has(tenantId))throw Error('unknown_tenant');if(!ROLES.includes(role))throw Error('invalid_role');const key=`${tenantId}:${userId}`;state.members.set(key,{tenantId,userId,role});audit(state,tenantId,'member.upserted',{userId,role});return state.members.get(key)}
export function authorize(state,{tenantId,userId,minimum='viewer'}){const m=state.members.get(`${tenantId}:${userId}`);if(!m)throw Error('membership_required');if(ROLES.indexOf(m.role)>ROLES.indexOf(minimum))throw Error('insufficient_role');return m}
export function issueApiKey(state,{tenantId,userId,label,secret='demo-secret'}){authorize(state,{tenantId,userId,minimum:'admin'});const id=`key_${hash(`${tenantId}:${label}`).slice(0,12)}`;const raw=`mts_${id}_${secret}`;state.apiKeys.set(id,{id,tenantId,label,keyHash:hash(raw),revoked:false});audit(state,tenantId,'api_key.issued',{id,label});return {id,token:raw}}
export function authenticate(state,token){const key=[...state.apiKeys.values()].find(k=>k.keyHash===hash(token));if(!key||key.revoked)throw Error('invalid_api_key');return key}
export function enqueueRun(state,{tenantId,workflowId,idempotencyKey,actorId}){authorize(state,{tenantId,userId:actorId,minimum:'operator'});if(!workflowId||!idempotencyKey)throw Error('invalid_run_request');const existing=[...state.runs.values()].find(r=>r.tenantId===tenantId&&r.idempotencyKey===idempotencyKey);if(existing)return {...existing,replayed:true};const tenant=state.tenants.get(tenantId);if(tenant.status!=='active')throw Error('tenant_inactive');if(tenant.usedRuns>=tenant.monthlyRunLimit)throw Error('quota_exceeded');const run={id:`run_${hash(`${tenantId}:${idempotencyKey}`).slice(0,14)}`,tenantId,workflowId,idempotencyKey,status:'queued',attempt:0,maxAttempts:3};state.runs.set(run.id,run);tenant.usedRuns++;audit(state,tenantId,'run.enqueued',{runId:run.id,workflowId});return run}
export function completeRun(state,{tenantId,runId,success,errorCode}){const run=state.runs.get(runId);if(!run||run.tenantId!==tenantId)throw Error('run_not_found');run.attempt++;if(success){run.status='succeeded';audit(state,tenantId,'run.succeeded',{runId});return run}if(run.attempt<run.maxAttempts){run.status='retry_scheduled';audit(state,tenantId,'run.retry_scheduled',{runId,attempt:run.attempt,errorCode});return run}run.status='dead_lettered';state.dlq.push({tenantId,runId,errorCode});audit(state,tenantId,'run.dead_lettered',{runId,errorCode});return run}
export function listTenantRuns(state,{tenantId,userId}){authorize(state,{tenantId,userId,minimum:'viewer'});return [...state.runs.values()].filter(r=>r.tenantId===tenantId)}
export function audit(state,tenantId,event,payload){const prev=state.audit.at(-1)?.hash||'GENESIS';const row={id:`aud_${state.audit.length+1}`,tenantId,event,payload,prevHash:prev};row.hash=hash(JSON.stringify(row));state.audit.push(row);return row}
export function verifyAudit(state){return state.audit.every((row,i)=>row.prevHash===(i?state.audit[i-1].hash:'GENESIS')&&row.hash===hash(JSON.stringify({id:row.id,tenantId:row.tenantId,event:row.event,payload:row.payload,prevHash:row.prevHash})))}
