import{createHash}from'node:crypto';
const CHANNELS=new Set(['email','sms','whatsapp','web']);const STATES={new:new Set(['triaged']),triaged:new Set(['invite_queued','recovery_open','escalated']),recovery_open:new Set(['in_progress','resolved','closed_unresolved']),in_progress:new Set(['resolved','closed_unresolved']),invite_queued:new Set(['invite_sent','delivery_failed']),invite_sent:new Set(['review_verified','expired']),resolved:new Set(),closed_unresolved:new Set(),review_verified:new Set(),delivery_failed:new Set(),expired:new Set(),escalated:new Set(['recovery_open'])};
const clean=v=>typeof v==='string'?v.trim():'';const scalar=v=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).filter(([,x])=>['string','number','boolean'].includes(typeof x))):{};
export function normalizeFeedback(input,now=new Date()){if(!input||typeof input!=='object'||Array.isArray(input))throw new TypeError('payload must be an object');const sourceEventId=clean(input.sourceEventId),channel=clean(input.channel).toLowerCase(),customerId=clean(input.customerId),serviceEventId=clean(input.serviceEventId),message=clean(input.message),rating=Number(input.rating);if(!sourceEventId)throw new RangeError('sourceEventId is required');if(!CHANNELS.has(channel))throw new RangeError('unsupported channel');if(!customerId)throw new RangeError('customerId is required');if(!serviceEventId)throw new RangeError('serviceEventId is required');if(!Number.isInteger(rating)||rating<1||rating>5)throw new RangeError('rating must be 1..5');return{schemaVersion:'1.0',sourceEventId,channel,customerId,serviceEventId,rating,message,consentToContact:input.consentToContact===true,optedOutOfReviewInvites:input.optedOutOfReviewInvites===true,serviceCompleted:input.serviceCompleted===true,receivedAt:input.receivedAt?new Date(input.receivedAt).toISOString():now.toISOString(),metadata:scalar(input.metadata)};}
export function idempotencyKey(f){return createHash('sha256').update(`${f.channel}:${f.sourceEventId}`).digest('hex');}
export function redactPII(text){return text.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[REDACTED_EMAIL]').replace(/\b(?:\d[ -]*?){13,19}\b/g,'[REDACTED_CARD]').replace(/\+?\d[\d\s().-]{7,}\d/g,'[REDACTED_PHONE]');}
const NEG=['bad','poor','terrible','late','broken','angry','refund','unsafe','rude','unhappy','disappointed'];const RISK=['unsafe','injury','threat','fraud','discrimination','legal','chargeback'];
export function classifyFeedback(f){const t=f.message.toLowerCase(),negative=NEG.filter(x=>t.includes(x)),risk=RISK.filter(x=>t.includes(x));const sentiment=f.rating<=2?'negative':f.rating===3?'neutral':'positive';return{sentiment,confidence:f.rating===3?0.72:0.94,risk:risk.length?'high':f.rating===1?'medium':'low',evidence:[...new Set([...negative,...risk])]};}
export function inviteEligibility(f,history={},now=new Date()){if(!f.serviceCompleted)return{eligible:false,reason:'service_not_completed'};if(f.optedOutOfReviewInvites)return{eligible:false,reason:'opted_out'};if(history.verifiedReview===true)return{eligible:false,reason:'already_reviewed'};if(history.lastInviteAt&&now-new Date(history.lastInviteAt)<30*86400000)return{eligible:false,reason:'cooldown'};return{eligible:true,reason:'eligible'};}
export function decideActions(f,classification,eligibility){const createRecovery=classification.sentiment==='negative'||classification.risk!=='low';return{queueNeutralReviewInvite:eligibility.eligible,createRecoveryCase:createRecovery,humanEscalation:classification.risk==='high',reviewGatingApplied:false,reason:createRecovery?'dissatisfaction_or_risk':'standard_followup'};}
export function analyzeFeedback(input,history={},now=new Date()){const feedback=normalizeFeedback(input,now),classification=classifyFeedback(feedback),eligibility=inviteEligibility(feedback,history,now),actions=decideActions(feedback,classification,eligibility);return{feedback:{...feedback,message:redactPII(feedback.message)},idempotencyKey:idempotencyKey(feedback),classification,eligibility,actions,evidenceType:'simulated'};}
export function canTransition(a,b){return STATES[a]?.has(b)??false;}
export function classifyDelivery(status,attempt,max=3){if(status>=200&&status<300)return'delivered';if((status===429||status>=500)&&attempt<max)return'retry';return'dlq';}
export function computeKpis(events){const verified=events.filter(x=>x.type==='review_verified').length,sent=events.filter(x=>x.type==='invite_sent').length,resolved=events.filter(x=>x.type==='recovery_resolved').length,opened=events.filter(x=>x.type==='recovery_opened').length;return{verifiedReviews:verified,reviewConversionRate:sent?verified/sent:0,recoveryResolutionRate:opened?resolved/opened:0};}
