import test from'node:test';import assert from'node:assert/strict';import*as c from'../src/core.mjs';
const now='2026-01-01T00:00:00.000Z',clock=()=>now;
function event(overrides={}){return{specversion:'1.0',id:'event-001',source:'urn:test:orders',type:'order.created',subject:'order-1',sequence:1,data:{amount:10},...overrides}}
function fixture(limit=10){const s=c.createState({clock}),a=c.provisionTenant(s,{slug:'alpha-co',name:'Alpha',monthlyEventLimit:limit}),b=c.provisionTenant(s,{slug:'beta-co',name:'Beta'});c.subscribe(s,{tenantId:a.id,eventType:'order.created',workflowId:'wf-a'});return{s,a,b}}
function ingest(s,tenantId,e=event(),timestamp=now){return c.ingestEvent(s,{tenantId,event:e,timestamp,signature:c.signEvent(s,{tenantId,timestamp,event:e})})}
for(const [name,input,code]of[['short slug',{slug:'x',name:'Ok'},'invalid_tenant_slug'],['bad slug',{slug:'Bad Slug',name:'Ok'},'invalid_tenant_slug'],['empty name',{slug:'valid-co',name:''},'invalid_tenant_name'],['string limit',{slug:'valid-co',name:'Ok',monthlyEventLimit:'2'},'invalid_event_limit'],['zero limit',{slug:'valid-co',name:'Ok',monthlyEventLimit:0},'invalid_event_limit']])test(`rejects ${name}`,()=>assert.throws(()=>c.provisionTenant(c.createState(),input),new RegExp(code)));
test('duplicate tenant conflicts',()=>{const{s}=fixture();assert.throws(()=>c.provisionTenant(s,{slug:'alpha-co',name:'Again'}),/tenant_exists/)});
test('api keys are random and raw token is not stored',()=>{const{s,a}=fixture(),x=c.issueApiKey(s,{tenantId:a.id}),y=c.issueApiKey(s,{tenantId:a.id});assert.notEqual(x.token,y.token);assert.equal(s.apiKeys.get(x.id).token,undefined)});
test('api key scope is enforced',()=>{const{s,a}=fixture(),k=c.issueApiKey(s,{tenantId:a.id,scopes:['events:read']});assert.throws(()=>c.authenticate(s,k.token,'events:write'),/insufficient_scope/)});
test('invalid api key is rejected',()=>assert.throws(()=>c.authenticate(c.createState(),'wrong'),/invalid_api_key/));
test('valid signed event is routed',()=>{const{s,a}=fixture(),r=ingest(s,a.id);assert.equal(r.routes,1);assert.equal(s.deliveries.size,1);assert.equal(s.outbox.length,1)});
test('tampered nested data invalidates signature',()=>{const{s,a}=fixture(),e=event(),signature=c.signEvent(s,{tenantId:a.id,timestamp:now,event:e});e.data.amount=999;assert.throws(()=>c.ingestEvent(s,{tenantId:a.id,event:e,timestamp:now,signature}),/invalid_signature/)});
test('expired signature timestamp rejected',()=>{const{s,a}=fixture(),e=event(),old='2025-12-31T23:00:00.000Z',signature=c.signEvent(s,{tenantId:a.id,timestamp:old,event:e});assert.throws(()=>c.ingestEvent(s,{tenantId:a.id,event:e,timestamp:old,signature}),/signature_expired/)});
test('wrong signature rejected',()=>{const{s,a}=fixture();assert.throws(()=>c.ingestEvent(s,{tenantId:a.id,event:event(),timestamp:now,signature:'bad'}),/invalid_signature/)});
for(const [name,change,code]of[['specversion',{specversion:'0.3'},'unsupported_specversion'],['id',{id:'x'},'invalid_event_id'],['type',{type:'unknown'},'unsupported_event_type'],['subject',{subject:''},'invalid_event_subject'],['sequence',{sequence:0},'invalid_sequence'],['data',{data:'x'},'invalid_event_data']])test(`rejects invalid ${name}`,()=>assert.throws(()=>c.validateEvent(event(change)),new RegExp(code)));
test('rejects unknown event field',()=>assert.throws(()=>c.validateEvent(event({unexpected:true})),/unknown_event_field/));
test('rejects invalid event time',()=>assert.throws(()=>c.validateEvent(event({time:'not-a-date'})),/invalid_event_time/));
test('rejects unsupported data content type',()=>assert.throws(()=>c.validateEvent(event({datacontenttype:'text/plain'})),/unsupported_content_type/));
test('oversized event rejected',()=>assert.throws(()=>c.validateEvent(event({data:{x:'a'.repeat(33000)}})),/event_too_large/));
test('deduplication consumes quota once',()=>{const{s,a}=fixture(),x=ingest(s,a.id),y=ingest(s,a.id);assert.equal(x.internalId,y.internalId);assert.equal(y.deduplicated,true);assert.equal(a.usedEvents,1);assert.equal(s.deliveries.size,1)});
test('same producer event id is isolated by tenant',()=>{const{s,a,b}=fixture(),e=event();ingest(s,a.id,e);ingest(s,b.id,e);assert.equal(s.events.size,2)});
test('quota returns 429',()=>{const{s,a}=fixture(1);ingest(s,a.id);assert.throws(()=>ingest(s,a.id,event({id:'event-002',subject:'order-2'})),e=>e.status===429)});
test('sequence gap is quarantined',()=>{const{s,a}=fixture(),r=ingest(s,a.id,event({sequence:2}));assert.equal(r.status,'quarantined');assert.equal(r.reason,'sequence_gap');assert.equal(s.quarantine[0].replayAuthorized,false)});
test('older sequence is quarantined',()=>{const{s,a}=fixture();ingest(s,a.id);const r=ingest(s,a.id,event({id:'event-002'}));assert.equal(r.status,'quarantined');assert.equal(r.reason,'out_of_order_or_replay')});
test('worker credential required',()=>{const{s,a}=fixture();ingest(s,a.id);const d=[...s.deliveries.values()][0];assert.throws(()=>c.completeDelivery(s,{tenantId:a.id,deliveryId:d.id,success:true,workerSecret:'bad'}),/invalid_worker/)});
test('cross tenant completion hidden',()=>{const{s,a,b}=fixture();ingest(s,a.id);const d=[...s.deliveries.values()][0];assert.throws(()=>c.completeDelivery(s,{tenantId:b.id,deliveryId:d.id,success:true,workerSecret:s.workerSecret}),/delivery_not_found/)});
test('successful delivery is terminal',()=>{const{s,a}=fixture();ingest(s,a.id);const d=[...s.deliveries.values()][0];c.completeDelivery(s,{tenantId:a.id,deliveryId:d.id,success:true,workerSecret:s.workerSecret});assert.throws(()=>c.completeDelivery(s,{tenantId:a.id,deliveryId:d.id,success:false,errorCode:'late',workerSecret:s.workerSecret}),/terminal_delivery/)});
test('bounded retry reaches dlq once',()=>{const{s,a}=fixture();ingest(s,a.id);const d=[...s.deliveries.values()][0];for(let i=0;i<3;i++)c.completeDelivery(s,{tenantId:a.id,deliveryId:d.id,success:false,errorCode:'timeout',workerSecret:s.workerSecret});assert.equal(d.status,'dead_lettered');assert.equal(s.dlq.length,1);assert.equal(s.dlq[0].replayAuthorized,false)});
test('retry backoff is deterministic and increasing',()=>{const{s,a}=fixture();ingest(s,a.id);const d=[...s.deliveries.values()][0];c.completeDelivery(s,{tenantId:a.id,deliveryId:d.id,success:false,errorCode:'timeout',workerSecret:s.workerSecret});assert.equal(d.nextAttemptAt,'2026-01-01T00:00:02.000Z')});
test('dlq replay requires recorded approval',()=>{const{s,a}=fixture();ingest(s,a.id);const d=[...s.deliveries.values()][0];for(let i=0;i<3;i++)c.completeDelivery(s,{tenantId:a.id,deliveryId:d.id,success:false,errorCode:'timeout',workerSecret:s.workerSecret});const row=c.authorizeReplay(s,{tenantId:a.id,deliveryId:d.id,approvedBy:'alice',reason:'upstream fixed'});assert.equal(row.replayAuthorized,true)});
test('audit tampering is tenant isolated',()=>{const{s,a,b}=fixture();assert.equal(c.verifyAudit(s,a.id),true);assert.equal(c.verifyAudit(s,b.id),true);s.audit.find(x=>x.tenantId===a.id).event='tampered';assert.equal(c.verifyAudit(s,a.id),false);assert.equal(c.verifyAudit(s,b.id),true)});
test('tenant event listing is isolated',()=>{const{s,a,b}=fixture();ingest(s,a.id);assert.equal(c.listTenantEvents(s,{tenantId:b.id}).length,0)});
