import test from'node:test';import assert from'node:assert/strict';import{buildServer}from'../src/server.mjs';import{createState,signEvent}from'../src/core.mjs';
async function setup(){const state=createState(),server=buildServer(state);await new Promise(ok=>server.listen(0,ok));return{state,server,base:`http://127.0.0.1:${server.address().port}`}}
async function api(base,path,{method='GET',body,headers={}}={}){const response=await fetch(base+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});return{status:response.status,headers:response.headers,json:await response.json()}}
test('health returns security headers',async()=>{const{server,base}=await setup(),r=await fetch(base+'/health');assert.equal(r.status,200);assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.ok(r.headers.get('x-request-id'));server.close()});
test('bootstrap credential is required',async()=>{const{server,base}=await setup(),r=await api(base,'/v1/tenants',{method:'POST',body:{}});assert.equal(r.status,403);server.close()});
test('malformed json returns 400',async()=>{const{server,base}=await setup(),r=await fetch(base+'/v1/tenants',{method:'POST',headers:{'content-type':'application/json','x-bootstrap-token':'bootstrap-test'},body:'{'});assert.equal(r.status,400);server.close()});
test('content type is required',async()=>{const{server,base}=await setup(),r=await fetch(base+'/v1/tenants',{method:'POST',headers:{'x-bootstrap-token':'bootstrap-test'},body:'x'});assert.equal(r.status,415);server.close()});
test('bearer credential is required',async()=>{const{server,base}=await setup(),r=await api(base,'/v1/events',{method:'POST',body:{}});assert.equal(r.status,401);server.close()});
test('credential tenant overrides request body',async()=>{const{server,base}=await setup(),p=await api(base,'/v1/tenants',{method:'POST',headers:{'x-bootstrap-token':'bootstrap-test'},body:{slug:'server-co',name:'Server'}}),token=p.json.apiKey.token,tenant=p.json.tenant;const sub=await api(base,'/v1/subscriptions',{method:'POST',headers:{authorization:`Bearer ${token}`},body:{tenantId:'victim',eventType:'order.created',workflowId:'wf'}});assert.equal(sub.status,201);assert.equal(sub.json.tenantId,tenant.id);server.close()});
test('signed event accepted through HTTP',async()=>{const{state,server,base}=await setup(),p=await api(base,'/v1/tenants',{method:'POST',headers:{'x-bootstrap-token':'bootstrap-test'},body:{slug:'event-co',name:'Event'}}),token=p.json.apiKey.token,tenant=p.json.tenant,event={specversion:'1.0',id:'event-http-1',source:'urn:http',type:'order.created',subject:'order-1',sequence:1,data:{ok:true}},timestamp=new Date().toISOString(),signature=signEvent(state,{tenantId:tenant.id,timestamp,event}),r=await api(base,'/v1/events',{method:'POST',headers:{authorization:`Bearer ${token}`,'x-event-timestamp':timestamp,'x-event-signature':signature},body:{tenantId:'victim',event}});assert.equal(r.status,202);assert.equal(r.json.tenantId,tenant.id);server.close()});
test('worker token is required for completion',async()=>{const{state,server,base}=await setup(),p=await api(base,'/v1/tenants',{method:'POST',headers:{'x-bootstrap-token':'bootstrap-test'},body:{slug:'worker-co',name:'Worker'}}),token=p.json.apiKey.token,tenant=p.json.tenant;await api(base,'/v1/subscriptions',{method:'POST',headers:{authorization:`Bearer ${token}`},body:{eventType:'order.created',workflowId:'wf'}});const event={specversion:'1.0',id:'event-worker-1',source:'urn:http',type:'order.created',subject:'order-1',sequence:1,data:{ok:true}},timestamp=new Date().toISOString(),signature=signEvent(state,{tenantId:tenant.id,timestamp,event});await api(base,'/v1/events',{method:'POST',headers:{authorization:`Bearer ${token}`,'x-event-timestamp':timestamp,'x-event-signature':signature},body:{event}});const delivery=[...state.deliveries.values()][0],r=await api(base,`/v1/deliveries/${delivery.id}/complete`,{method:'POST',headers:{authorization:`Bearer ${token}`},body:{success:true}});assert.equal(r.status,403);server.close()});
