import test from'node:test';import assert from'node:assert/strict';import*as c from'../src/core.mjs';const clock=()=> '2026-01-01T00:00:00.000Z';function f(){const s=c.createState({clock}),a=c.provisionTenant(s,{slug:'alpha-co',name:'Alpha',ownerUserId:'alice',monthlyRunLimit:2}),b=c.provisionTenant(s,{slug:'beta-co',name:'Beta',ownerUserId:'bob'});c.addMember(s,{tenantId:a.id,actorId:'alice',userId:'olivia',role:'operator'});return{s,a,b}}
for(const [name,input,err] of [['short slug',{slug:'a',name:'A',ownerUserId:'xx'},'invalid_tenant_slug'],['empty name',{slug:'valid-co',name:'',ownerUserId:'xx'},'invalid_tenant_name'],['bad plan',{slug:'valid-co',name:'Ok',ownerUserId:'xx',plan:'gold'},'invalid_plan'],['string quota',{slug:'valid-co',name:'Ok',ownerUserId:'xx',monthlyRunLimit:'5'},'invalid_run_limit'],['zero quota',{slug:'valid-co',name:'Ok',ownerUserId:'xx',monthlyRunLimit:0},'invalid_run_limit']])test(`rejects ${name}`,()=>assert.throws(()=>c.provisionTenant(c.createState(),input),new RegExp(err)));
test('duplicate tenant conflicts',()=>{const{s}=f();assert.throws(()=>c.provisionTenant(s,{slug:'alpha-co',name:'XX',ownerUserId:'xx'}),/tenant_exists/)});
test('self promotion is forbidden',()=>{const{s,a}=f();assert.throws(()=>c.addMember(s,{tenantId:a.id,actorId:'mallory',userId:'mallory',role:'owner'}),/membership_required/)});
test('operator cannot promote members',()=>{const{s,a}=f();assert.throws(()=>c.addMember(s,{tenantId:a.id,actorId:'olivia',userId:'x',role:'admin'}),/insufficient_role/)});
test('admin can add viewer',()=>{const{s,a}=f();c.addMember(s,{tenantId:a.id,actorId:'alice',userId:'ann',role:'admin'});assert.equal(c.addMember(s,{tenantId:a.id,actorId:'ann',userId:'vv',role:'viewer'}).role,'viewer')});
test('tenant isolation',()=>{const{s,a,b}=f(),r=c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:'12345678',actorId:'olivia'});assert.throws(()=>c.completeRun(s,{tenantId:b.id,runId:r.id,success:true,workerSecret:s.workerSecret}),/run_not_found/);assert.deepEqual(c.listTenantRuns(s,{tenantId:b.id,userId:'bob'}),[])});
test('api keys are random',()=>{const{s,a}=f(),x=c.issueApiKey(s,{tenantId:a.id,actorId:'alice',label:'one'}),y=c.issueApiKey(s,{tenantId:a.id,actorId:'alice',label:'one'});assert.notEqual(x.token,y.token);assert.equal(s.apiKeys.get(x.id).token,undefined)});
test('scope enforced',()=>{const{s,a}=f(),k=c.issueApiKey(s,{tenantId:a.id,actorId:'alice',label:'read',scopes:['runs:read']});assert.throws(()=>c.authenticate(s,k.token,'runs:write'),/insufficient_scope/)});
test('revocation enforced',()=>{const{s,a}=f(),k=c.issueApiKey(s,{tenantId:a.id,actorId:'alice',label:'key',scopes:['keys:write']});c.revokeApiKey(s,{tenantId:a.id,actorId:'alice',keyId:k.id});assert.throws(()=>c.authenticate(s,k.token),/invalid_api_key/)});
test('invalid token rejected',()=>assert.throws(()=>c.authenticate(c.createState(),'bad'),/invalid_api_key/));
test('idempotency consumes once',()=>{const{s,a}=f(),x={tenantId:a.id,workflowId:'wf',idempotencyKey:'same-key',actorId:'olivia'};c.enqueueRun(s,x);assert.equal(c.enqueueRun(s,x).replayed,true);assert.equal(a.usedRuns,1)});
test('short idempotency rejected',()=>{const{s,a}=f();assert.throws(()=>c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:'x',actorId:'olivia'}),/invalid_idempotency_key/)});
test('quota returns 429',()=>{const{s,a}=f();for(const k of['12345678','87654321'])c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:k,actorId:'olivia'});try{c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:'11111111',actorId:'olivia'});assert.fail()}catch(e){assert.equal(e.status,429)}});
test('worker credential required',()=>{const{s,a}=f(),r=c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:'12345678',actorId:'olivia'});assert.throws(()=>c.completeRun(s,{tenantId:a.id,runId:r.id,success:true,workerSecret:'bad'}),/invalid_worker/)});
test('terminal success immutable',()=>{const{s,a}=f(),r=c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:'12345678',actorId:'olivia'});c.completeRun(s,{tenantId:a.id,runId:r.id,success:true,workerSecret:s.workerSecret});assert.throws(()=>c.completeRun(s,{tenantId:a.id,runId:r.id,success:false,errorCode:'late',workerSecret:s.workerSecret}),/terminal_run/)});
test('bounded retry reaches dlq once',()=>{const{s,a}=f(),r=c.enqueueRun(s,{tenantId:a.id,workflowId:'wf',idempotencyKey:'12345678',actorId:'olivia'});for(let i=0;i<3;i++)c.completeRun(s,{tenantId:a.id,runId:r.id,success:false,errorCode:'timeout',workerSecret:s.workerSecret});assert.equal(s.dlq.length,1);assert.equal(s.dlq[0].replayAuthorized,false)});
test('per tenant audit verifies',()=>{const{s,a,b}=f();assert.equal(c.verifyAudit(s,a.id),true);assert.equal(c.verifyAudit(s,b.id),true);s.audit.find(x=>x.tenantId===a.id).event='tamper';assert.equal(c.verifyAudit(s,a.id),false);assert.equal(c.verifyAudit(s,b.id),true)});
