import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {normalizeBrief,normalizeBrandMemory,briefKey,packageKey,validateClaims,producePackage,qualityGate,transitionPackage,buildExportManifest,classifyDelivery,computeKpis} from '../src/core.mjs';

const load=async path=>JSON.parse(await readFile(new URL(path,import.meta.url)));
const brief=await load('../examples/valid-content-brief.json');
const brand=await load('../brand/default-brand-memory.json');

test('normalizes a complete brief',()=>assert.equal(normalizeBrief(brief).schemaVersion,'1.0'));
test('normalizes brand memory',()=>assert.equal(normalizeBrandMemory(brand).version,1));
test('rejects missing brief fields',()=>assert.throws(()=>normalizeBrief({...brief,title:''}),/missing title/));
test('rejects unsupported formats',()=>assert.throws(()=>normalizeBrief({...brief,formats:['podcast']}),/invalid formats/));
test('rejects duplicate formats',()=>assert.throws(()=>normalizeBrief({...brief,formats:['email','email']}),/invalid formats/));
test('rejects unsafe evidence URLs',()=>assert.throws(()=>normalizeBrief({...brief,evidence:[{...brief.evidence[0],sourceUrl:'file:///etc/passwd'}]}),/unsafe evidence URL/));
test('rejects duplicate evidence identities',()=>assert.throws(()=>normalizeBrief({...brief,evidence:[brief.evidence[0],brief.evidence[0]]}),/duplicate evidence/));
test('rejects duplicate claim identities',()=>assert.throws(()=>normalizeBrief({...brief,claims:[brief.claims[0],brief.claims[0]]}),/duplicate claim/));
test('brief identity is deterministic',()=>assert.equal(briefKey(normalizeBrief(brief)),briefKey(normalizeBrief(brief))));
test('package identity is version scoped',()=>assert.notEqual(packageKey(normalizeBrief(brief),1),packageKey(normalizeBrief(brief),2)));
test('valid claims have no findings',()=>assert.deepEqual(validateClaims(normalizeBrief(brief)),[]));
test('flags unsupported factual claims',()=>{const b=normalizeBrief({...brief,claims:[{...brief.claims[0],evidenceIds:[]}]});assert.equal(validateClaims(b)[0].code,'unsupported_factual_claim')});
test('flags unknown evidence references',()=>{const b=normalizeBrief({...brief,claims:[{...brief.claims[0],evidenceIds:['missing']}]});assert.ok(validateClaims(b).some(x=>x.code==='unknown_evidence_reference'))});
test('flags prompt injection in evidence',async()=>{const b=normalizeBrief(await load('../examples/injection-brief.json'));assert.ok(validateClaims(b).some(x=>x.code==='prompt_injection_evidence'))});
test('produces all five requested formats',()=>assert.equal(Object.keys(producePackage(brief,brand)).length>0&&Object.keys(producePackage(brief,brand).variants).length,5));
test('production is deterministic',()=>assert.equal(producePackage(brief,brand).fingerprint,producePackage(brief,brand).fingerprint));
test('package versions have different fingerprints',()=>assert.notEqual(producePackage(brief,brand,1).fingerprint,producePackage(brief,brand,2).fingerprint));
test('brand version must match',()=>assert.throws(()=>producePackage(brief,{...brand,version:2}),/brand version mismatch/));
test('visual brief includes accessible alt text',()=>assert.ok(producePackage(brief,brand).visualBrief.requiredAssets.every(x=>x.altText)));
test('valid package proceeds to human review',()=>{const q=qualityGate(producePackage(brief,brand),brief,brand);assert.equal(q.decision,'needs_review');assert.equal(q.passed,true)});
test('QA detects missing format',()=>{const p=producePackage(brief,brand);delete p.variants.email;assert.ok(qualityGate(p,brief,brand).findings.some(x=>x.code==='missing_format'))});
test('QA detects missing carousel alt text',()=>{const p=producePackage(brief,brand);p.variants.carousel.slides[0].altText='';assert.ok(qualityGate(p,brief,brand).findings.some(x=>x.code==='missing_alt_text'))});
test('QA detects PII',()=>{const p=producePackage(brief,brand);p.variants.email.body+=' test@example.com';assert.ok(qualityGate(p,brief,brand).findings.some(x=>x.code==='pii_detected'))});
test('sensitive claims require legal review',()=>{const b={...brief,claims:[{...brief.claims[0],text:'This is financial advice'}]};const q=qualityGate(producePackage(b,brand),b,brand);assert.ok(q.requiredRoles.includes('legal_reviewer'))});
test('invalid state transition is rejected',()=>assert.throws(()=>transitionPackage(producePackage(brief,brand),'released','a','brand_reviewer'),/invalid transition/));
test('approval matrix blocks missing roles',()=>{const p={...producePackage(brief,brand),status:'needs_review'};assert.throws(()=>transitionPackage(p,'approved','a','brand_reviewer',['brand_reviewer','factual_reviewer'],[]),/missing approvals/)});
test('approval matrix accepts all roles',()=>{const p={...producePackage(brief,brand),status:'needs_review'};const out=transitionPackage(p,'approved','a','factual_reviewer',['brand_reviewer','factual_reviewer'],[{role:'brand_reviewer',status:'approved'}]);assert.equal(out.status,'approved')});
test('export requires approval',()=>assert.throws(()=>buildExportManifest(producePackage(brief,brand),[]),/approved package/));
test('export manifest fingerprints every file',()=>{const p={...producePackage(brief,brand),status:'approved'};const m=buildExportManifest(p,[]);assert.equal(m.files.length,5);assert.ok(m.files.every(x=>x.sha256.length===64))});
test('delivery classification is bounded',()=>{assert.equal(classifyDelivery(202,1),'delivered');assert.equal(classifyDelivery(429,1),'retry');assert.equal(classifyDelivery(500,3),'dlq');assert.equal(classifyDelivery(422,1),'dlq')});
test('KPI counts only provider verified releases',()=>{const k=computeKpis([{type:'package_released',evidence:'simulated'},{type:'package_released',evidence:'provider_verified'}]);assert.equal(k.providerVerifiedReleases,1);assert.equal(k.simulatedBusinessOutcome,false)});
