import{createHash}from'node:crypto';
const CURRENCIES=new Set(['USD','CAD','EUR']);
const transitions={draft:['pending_approval','void'],pending_approval:['approved','rejected','void'],approved:['sent','void'],sent:['accepted','expired','void'],accepted:['invoiced','void'],invoiced:['partially_paid','paid','overdue','void'],partially_paid:['paid','overdue'],overdue:['partially_paid','paid','written_off'],paid:['refunded'],rejected:[],expired:[],void:[],written_off:[],refunded:[]};
export function normalizeRequest(input){if(!input||typeof input!=='object')throw new Error('quote request required');for(const k of['sourceEventId','customerId','currency','items'])if(input[k]===undefined||input[k]==='')throw new Error(`missing ${k}`);if(!CURRENCIES.has(String(input.currency).toUpperCase()))throw new Error('unsupported currency');if(!Array.isArray(input.items)||input.items.length<1||input.items.length>100)throw new Error('items must contain 1..100 lines');const items=input.items.map((x,i)=>{for(const k of['sku','description','quantity','unitPriceMinor'])if(x[k]===undefined||x[k]==='')throw new Error(`item ${i} missing ${k}`);const quantity=Number(x.quantity),unitPriceMinor=Number(x.unitPriceMinor),taxRateBps=Number(x.taxRateBps??0);if(!Number.isInteger(quantity)||quantity<1||!Number.isSafeInteger(unitPriceMinor)||unitPriceMinor<0||!Number.isInteger(taxRateBps)||taxRateBps<0||taxRateBps>10000)throw new Error(`invalid item ${i}`);return{sku:String(x.sku).trim(),description:String(x.description).trim(),quantity,unitPriceMinor,taxRateBps}});const discountBps=Number(input.discountBps??0),validDays=Number(input.validDays??14);if(!Number.isInteger(discountBps)||discountBps<0||discountBps>10000)throw new Error('invalid discount');if(!Number.isInteger(validDays)||validDays<1||validDays>90)throw new Error('invalid validity');return{schemaVersion:'1.0',sourceEventId:String(input.sourceEventId).trim(),customerId:String(input.customerId).trim(),currency:String(input.currency).toUpperCase(),items,discountBps,validDays,requestedBy:String(input.requestedBy??'system').trim(),metadata:input.metadata??{}}}
export function eventKey(sourceEventId){return createHash('sha256').update(`quote:${sourceEventId}`).digest('hex')}
export function calculateQuote(q){const subtotalMinor=q.items.reduce((s,x)=>s+x.quantity*x.unitPriceMinor,0);if(!Number.isSafeInteger(subtotalMinor))throw new Error('amount overflow');const discountMinor=Math.round(subtotalMinor*q.discountBps/10000);const taxableBase=subtotalMinor-discountMinor;const taxMinor=q.items.reduce((s,x)=>{const gross=x.quantity*x.unitPriceMinor;const allocatedDiscount=Math.round(gross*q.discountBps/10000);return s+Math.round((gross-allocatedDiscount)*x.taxRateBps/10000)},0);const totalMinor=taxableBase+taxMinor;return{subtotalMinor,discountMinor,taxMinor,totalMinor,currency:q.currency}}
export function approvalPlan(q,t){const amount=t.totalMinor;const reasons=[];const approvers=[];if(q.discountBps>1000){reasons.push('discount_above_10_percent');approvers.push('sales_manager')}if(amount>=1000000){reasons.push('high_value_quote');approvers.push('finance')}if(amount>=5000000){reasons.push('executive_threshold');approvers.push('executive')}return{required:approvers.length>0,approvers:[...new Set(approvers)],reasons}}
export function canTransition(from,to){return(transitions[from]??[]).includes(to)}
export function transition(entity,to,actor,now=new Date()){if(!actor)throw new Error('actor required');if(!canTransition(entity.status,to))throw new Error(`invalid transition ${entity.status}->${to}`);return{...entity,status:to,updatedAt:now.toISOString(),lastActor:actor}}
export function buildInvoice(quote,number,now=new Date()){if(quote.status!=='accepted')throw new Error('accepted quote required');return{invoiceNumber:number,quoteId:quote.id,quoteVersion:quote.version,currency:quote.currency,totalMinor:quote.totalMinor,amountPaidMinor:0,balanceMinor:quote.totalMinor,status:'open',issuedAt:now.toISOString()}}
export function paymentKey(provider,providerEventId){if(!provider||!providerEventId)throw new Error('provider identity required');return createHash('sha256').update(`${provider}:${providerEventId}`).digest('hex')}
export function reconcilePayment(invoice,event){if(event.currency!==invoice.currency)return{matched:false,reason:'currency_mismatch'};if(event.invoiceNumber!==invoice.invoiceNumber)return{matched:false,reason:'invoice_mismatch'};if(!Number.isSafeInteger(event.amountMinor)||event.amountMinor<=0)return{matched:false,reason:'invalid_amount'};const amountPaidMinor=invoice.amountPaidMinor+event.amountMinor;if(amountPaidMinor>invoice.totalMinor)return{matched:false,reason:'overpayment_requires_review'};const balanceMinor=invoice.totalMinor-amountPaidMinor;return{matched:true,amountPaidMinor,balanceMinor,status:balanceMinor===0?'paid':'partially_paid'}}
export function computeKpis(events){const quotes=events.filter(x=>x.type==='quote_sent').length,accepted=events.filter(x=>x.type==='quote_accepted').length,invoiced=events.filter(x=>x.type==='invoice_issued').reduce((s,x)=>s+x.amountMinor,0),cash=events.filter(x=>x.type==='payment_reconciled'&&x.evidence==='provider_verified').reduce((s,x)=>s+x.amountMinor,0);return{quotesSent:quotes,quoteAcceptanceRate:quotes?accepted/quotes:0,invoicedMinor:invoiced,reconciledCashMinor:cash}}
export function classifyDelivery(status,attempt,max=3){if(status>=200&&status<300)return'delivered';if((status===429||status>=500)&&attempt<max)return'retry';return'dlq'}
