import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {readFile} from 'node:fs/promises';import {createServer} from '../src/server.mjs';
const fixture=JSON.parse(await readFile(new URL('../examples/synthetic-customer-case.json',import.meta.url),'utf8'));
async function withServer(fn){const server=createServer().listen(0,'127.0.0.1');await once(server,'listening');try{return await fn(`http://127.0.0.1:${server.address().port}`);}finally{server.close();await once(server,'close');}}
test('health endpoint exposes safety boundary',()=>withServer(async base=>{const r=await fetch(`${base}/health`);assert.equal(r.status,200);const b=await r.json();assert.equal(b.autoSend,false);assert.equal(b.deliveryMode,'mock');assert.equal(b.causalClaimAllowed,false);}));
test('health score endpoint works',()=>withServer(async base=>{const r=await fetch(`${base}/health-score`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({case:fixture})});assert.equal(r.status,200);assert.equal((await r.json()).healthScore,53.5);}));
test('recommend endpoint requires approval',()=>withServer(async base=>{const r=await fetch(`${base}/recommend`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({case:fixture,channel:'email'})});assert.equal((await r.json()).status,'approval_required');}));
test('invalid JSON returns 400',()=>withServer(async base=>{const r=await fetch(`${base}/recommend`,{method:'POST',body:'{'});assert.equal(r.status,400);}));
test('unknown route returns 404',()=>withServer(async base=>assert.equal((await fetch(`${base}/missing`)).status,404)));
test('metrics endpoint returns prometheus text',()=>withServer(async base=>{const r=await fetch(`${base}/metrics`);assert.match(await r.text(),/customer_success_requests_total/);}));
