import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{normalizeExperiment,experimentKey,eventKey,assignVariant,validateLaunch,normalizeEvent,deduplicateEvents,validateAttribution,analyzeExperiment,recommendNextAction}from'../src/core.mjs';
const load=p=>readFile(new URL(p,import.meta.url)).then(JSON.parse);const exp=await load('../examples/experiment.json');const sample=await load('../examples/events.json');
const many=(variant,count,conv)=>Array.from({length:count},(_,i)=>[{provider:'mock',providerEventId:`${variant}-x-${i}`,subjectId:`${variant}-${i}`,eventType:'exposure',variantId:variant,occurredAt:'2026-09-02T09:00:00Z',consent:true},...(i<conv?[{provider:'mock',providerEventId:`${variant}-c-${i}`,subjectId:`${variant}-${i}`,eventType:'conversion',variantId:variant,outcome:'demo_booked',occurredAt:'2026-09-02T10:00:00Z',consent:true}]:[])]).flat();
test('normalizes experiment',()=>assert.equal(normalizeExperiment(exp).primaryOutcome,'demo_booked'));
test('requires exactly one control',()=>assert.throws(()=>normalizeExperiment({...exp,variants:exp.variants.map(x=>({...x,isControl:false}))}),/variants/));
test('requires consent guardrail',()=>assert.throws(()=>normalizeExperiment({...exp,guardrails:{}}),/consent/));
test('rejects invalid time window',()=>assert.throws(()=>normalizeExperiment({...exp,endsAt:exp.startsAt}),/window/));
test('experiment identity is stable',()=>assert.equal(experimentKey(exp),experimentKey(exp)));
test('assignment is stable and bounded',()=>{const a=assignVariant(exp,'visitor-a');assert.equal(a,assignVariant(exp,'visitor-a'));assert.ok(['control','treatment'].includes(a));});
test('launch rejects overlapping channel experiment',()=>assert.equal(validateLaunch(exp,[{...exp,experimentId:'other'}]).passed,false));
test('launch flags weak minimum sample',()=>assert.ok(validateLaunch({...exp,guardrails:{...exp.guardrails,minSamplePerVariant:10}}).findings.some(x=>x.code==='min_sample_too_low')));
test('normalizes consented event',()=>assert.equal(normalizeEvent(sample[0],exp).eventType,'exposure'));
test('event requires consent',()=>assert.throws(()=>normalizeEvent({...sample[0],consent:false},exp),/consent/));
test('event rejects unknown variant and outside date',()=>{assert.throws(()=>normalizeEvent({...sample[0],variantId:'other'},exp),/variant/);assert.throws(()=>normalizeEvent({...sample[0],occurredAt:'2026-10-02T00:00:00Z'},exp),/window/)});
test('provider event identity is stable',()=>assert.equal(eventKey(sample[0]),eventKey(sample[0])));
test('deduplicates provider events',()=>{const d=deduplicateEvents([sample[0],sample[0]],exp);assert.equal(d.accepted.length,1);assert.equal(d.duplicates.length,1)});
test('attribution needs exposure',()=>assert.ok(validateAttribution([sample[1]],exp).findings.some(x=>x.code==='conversion_without_exposure')));
test('attribution rejects window and variant mismatch',()=>{const late={...sample[1],occurredAt:'2026-09-15T10:00:00Z'};const wrong={...sample[1],variantId:'treatment'};assert.ok(validateAttribution([sample[0],late],exp).findings.some(x=>x.code==='conversion_outside_window'));assert.ok(validateAttribution([sample[0],wrong],exp).findings.some(x=>x.code==='variant_identity_mismatch'))});
test('small sample stays insufficient',()=>assert.equal(analyzeExperiment(sample,exp).significance.status,'insufficient_sample'));
test('analysis finds significant positive lift',()=>{const a=analyzeExperiment([...many('control',120,10),...many('treatment',120,35)],exp);assert.equal(a.significance.status,'statistically_significant');assert.ok(a.lift>0);assert.equal(recommendNextAction(a).action,'consider_rollout')});
test('analysis can retain control',()=>{const a=analyzeExperiment([...many('control',120,35),...many('treatment',120,10)],exp);assert.equal(recommendNextAction(a).action,'retain_control')});
test('verified revenue only appears on verified conversion',()=>{const events=[...many('control',100,5),...many('treatment',100,10)];events.find(x=>x.eventType==='conversion').providerVerified=true;events.find(x=>x.eventType==='conversion').amountMinor=1000;const a=analyzeExperiment(events,exp);assert.equal(a.variants.reduce((n,x)=>n+x.verifiedRevenueMinor,0),1000);assert.equal(a.simulatedBusinessOutcome,true)});
