import{createHash}from'node:crypto';
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const RISKY=/ignore (?:all|previous).*instructions|reveal (?:the )?(?:system prompt|secret|token)|execute (?:this )?(?:code|command)|<script|javascript:/i;
const SENSITIVE=/\b(?:social security|passport|credit card|bank account|medical record|private phone|personal email)\b/i;
const CONTACT=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b|\+?\d[\d ()-]{8,}\d/i;
const ALLOWED_AGENTS=new Set(['coordinator','company_researcher','evidence_verifier','opportunity_analyst','brief_composer']);
const ALLOWED_TOOLS=new Set(['fixture_search','source_reader','claim_extractor','evidence_matcher','brief_writer']);
const ALLOWED_SOURCE_TYPES=new Set(['official_company','regulatory_filing','reputable_press','customer_review_aggregate','public_job_posting']);
export function scanResearchText(value){const text=clean(value),findings=[];if(RISKY.test(text))findings.push({code:'prompt_injection',severity:'block'});if(SENSITIVE.test(text))findings.push({code:'sensitive_personal_data',severity:'block'});if(CONTACT.test(text))findings.push({code:'direct_contact_data',severity:'block'});return findings;}
export function normalizeResearchRequest(raw){for(const k of['requestId','version','accountName','accountDomain','researchPurpose','requestedBy'])if(!clean(raw?.[k]))throw new Error(`missing ${k}`);if(!/^([a-z0-9-]+\.)+[a-z]{2,}$/i.test(raw.accountDomain))throw new Error('invalid accountDomain');if(scanResearchText([raw.accountName,raw.researchPurpose,raw.requestedBy].join(' ')).some(x=>x.severity==='block'))throw new Error('unsafe research request');const allowedDomains=[...new Set((raw.allowedDomains??[]).map(x=>clean(x).toLowerCase()))];if(!allowedDomains.length)throw new Error('allowedDomains required');if(!allowedDomains.includes(clean(raw.accountDomain).toLowerCase()))throw new Error('account domain not allowlisted');const maxAgentSteps=Number(raw.maxAgentSteps??12),maxSources=Number(raw.maxSources??20);if(!Number.isInteger(maxAgentSteps)||maxAgentSteps<1||maxAgentSteps>30)throw new Error('invalid maxAgentSteps');if(!Number.isInteger(maxSources)||maxSources<1||maxSources>50)throw new Error('invalid maxSources');const asOf=new Date(raw.asOf??'2026-01-15T00:00:00Z');if(Number.isNaN(asOf.valueOf()))throw new Error('invalid asOf');return{requestId:clean(raw.requestId),version:clean(raw.version),accountName:clean(raw.accountName),accountDomain:clean(raw.accountDomain).toLowerCase(),researchPurpose:clean(raw.researchPurpose),requestedBy:clean(raw.requestedBy),allowedDomains:allowedDomains.sort(),maxAgentSteps,maxSources,asOf:asOf.toISOString(),evidenceBoundary:clean(raw.evidenceBoundary||'simulated')};}
export function validateAgentPlan(plan,request){const r=normalizeResearchRequest(request);if(!Array.isArray(plan)||!plan.length)throw new Error('agent plan required');if(plan.length>r.maxAgentSteps)throw new Error('agent step budget exceeded');const ids=new Set();return plan.map((s,i)=>{for(const k of['stepId','agent','tool','objective'])if(!clean(s?.[k]))throw new Error(`missing plan ${k} ${i}`);if(ids.has(s.stepId))throw new Error('duplicate stepId');ids.add(s.stepId);if(!ALLOWED_AGENTS.has(s.agent))throw new Error('unapproved agent');if(!ALLOWED_TOOLS.has(s.tool))throw new Error('unapproved tool');if(scanResearchText(s.objective).some(x=>x.severity==='block'))throw new Error('unsafe agent objective');return{stepId:clean(s.stepId),agent:s.agent,tool:s.tool,objective:clean(s.objective),dependsOn:[...new Set((s.dependsOn??[]).map(clean))].sort()};});}
export function normalizeSources(sources,request){const r=normalizeResearchRequest(request);if(!Array.isArray(sources)||!sources.length)throw new Error('sources required');if(sources.length>r.maxSources)throw new Error('source budget exceeded');const ids=new Set();return sources.map((s,i)=>{for(const k of['sourceId','url','title','sourceType','publishedAt','content'])if(!clean(s?.[k]))throw new Error(`missing source ${k} ${i}`);if(ids.has(s.sourceId))throw new Error('duplicate sourceId');ids.add(s.sourceId);let url;try{url=new URL(s.url)}catch{throw new Error('invalid source URL')}if(url.protocol!=='https:')throw new Error('https source required');if(!r.allowedDomains.some(d=>url.hostname===d||url.hostname.endsWith(`.${d}`)))throw new Error('source domain not allowlisted');if(!ALLOWED_SOURCE_TYPES.has(s.sourceType))throw new Error('unapproved source type');const safety=scanResearchText(s.content);if(safety.some(x=>x.severity==='block'))throw new Error('unsafe source content');const publishedAt=new Date(s.publishedAt);if(Number.isNaN(publishedAt.valueOf()))throw new Error('invalid source date');return{sourceId:clean(s.sourceId),url:url.href,title:clean(s.title),sourceType:s.sourceType,publishedAt:publishedAt.toISOString(),content:clean(s.content),publisher:clean(s.publisher),synthetic:s.synthetic===true};});}
function sourceQuality(type){return{official_company:.85,regulatory_filing:.95,reputable_press:.8,customer_review_aggregate:.65,public_job_posting:.7}[type]??0;}
export function verifyClaims(claims,sources,request){const r=normalizeResearchRequest(request),rows=normalizeSources(sources,r),map=new Map(rows.map(x=>[x.sourceId,x]));if(!Array.isArray(claims)||!claims.length)throw new Error('claims required');const asOf=new Date(r.asOf);return claims.map((c,i)=>{if(!clean(c?.claimId)||!clean(c?.statement))throw new Error(`missing claim ${i}`);if(scanResearchText(c.statement).some(x=>x.severity==='block'))throw new Error('unsafe claim');const sourceIds=[...new Set((c.sourceIds??[]).map(clean))].sort();if(!sourceIds.length)throw new Error('claim citation required');if(sourceIds.some(id=>!map.has(id)))throw new Error('unknown source citation');const cited=sourceIds.map(id=>map.get(id)),publishers=new Set(cited.map(x=>x.publisher||new URL(x.url).hostname));const ages=cited.map(x=>Math.floor((asOf-new Date(x.publishedAt))/86400000)),stale=ages.some(x=>x<0||x>730);const independent=publishers.size;const avgQuality=cited.reduce((n,x)=>n+sourceQuality(x.sourceType),0)/cited.length;const confidence=Number(Math.max(0,Math.min(1,avgQuality*(independent>=2?1:.72)*(stale?.65:1))).toFixed(4));const highImpact=c.importance==='high';const status=stale?'stale':highImpact&&independent<2?'needs_corroboration':confidence>=.75?'verified':confidence>=.5?'qualified':'weak';return{claimId:clean(c.claimId),statement:clean(c.statement),category:clean(c.category),importance:clean(c.importance||'medium'),sourceIds,independentSources:independent,confidence,status,stale};});}
export function detectContradictions(claims){const byTopic=new Map();for(const c of claims){const topic=clean(c.topic||c.category||c.claimId);if(!byTopic.has(topic))byTopic.set(topic,[]);byTopic.get(topic).push(c);}const contradictions=[];for(const[topic,rows]of byTopic)for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++)if(clean(rows[i].polarity)&&clean(rows[j].polarity)&&rows[i].polarity!==rows[j].polarity)contradictions.push({topic,claimIds:[rows[i].claimId,rows[j].claimId].sort(),status:'human_review_required'});return contradictions;}
export function buildAccountBrief(input){const request=normalizeResearchRequest(input.request),plan=validateAgentPlan(input.plan,request),sources=normalizeSources(input.sources,request),verifiedClaims=verifyClaims(input.claims,sources,request),contradictions=detectContradictions(input.claims),usable=verifiedClaims.filter(x=>['verified','qualified'].includes(x.status)),blocked=verifiedClaims.filter(x=>!['verified','qualified'].includes(x.status));const highImpactBlocked=blocked.some(x=>x.importance==='high'),status=contradictions.length||highImpactBlocked?'review_required':usable.length?'ready_for_human_review':'blocked';const brief={requestId:request.requestId,requestVersion:request.version,accountName:request.accountName,status,summary:clean(input.summary),verifiedClaims:usable,withheldClaims:blocked,contradictions,agentTrace:plan.map(x=>({stepId:x.stepId,agent:x.agent,tool:x.tool})),sourceManifest:sources.map(x=>({sourceId:x.sourceId,url:x.url,publishedAt:x.publishedAt,synthetic:x.synthetic})),recommendedNextSteps:(input.recommendedNextSteps??[]).map(clean).filter(Boolean),evidenceBoundary:request.evidenceBoundary,requiresHumanApproval:true,autoOutreach:false,autoCrmWrite:false};return{...brief,briefFingerprint:hash(brief)};}
export function reviewBrief(brief,review){for(const k of['reviewerId','reviewerRole','decision','rationale'])if(!clean(review?.[k]))throw new Error(`missing review ${k}`);if(!['sales_research_lead','account_executive','compliance_reviewer'].includes(review.reviewerRole))throw new Error('unauthorized reviewer');if(!['approve','reject','request_changes'].includes(review.decision))throw new Error('invalid review decision');if(brief.status==='blocked'&&review.decision==='approve')throw new Error('blocked brief cannot be approved');if(brief.contradictions?.length&&review.decision==='approve'&&review.reviewerRole!=='sales_research_lead')throw new Error('research lead required for contradictions');return{briefFingerprint:brief.briefFingerprint,reviewerId:clean(review.reviewerId),reviewerRole:review.reviewerRole,decision:review.decision,rationale:clean(review.rationale),reviewedAt:clean(review.reviewedAt||'2026-01-15T00:00:00Z'),outreachAuthorized:false,crmWriteAuthorized:false,auditFingerprint:hash({briefFingerprint:brief.briefFingerprint,review})};}
export function nextRetry(job){const attempts=Number(job?.attempts??0),maxAttempts=Number(job?.maxAttempts??3);if(!Number.isInteger(attempts)||!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>5)throw new Error('invalid retry policy');if(attempts>=maxAttempts)return{jobId:clean(job.jobId),action:'dlq',attempts,maxAttempts,reason:clean(job.lastError),autoReplay:false};return{jobId:clean(job.jobId),action:'retry',attempts:attempts+1,maxAttempts,delaySeconds:Math.min(300,2**attempts*15)};}
export function buildExportManifest(brief,review){if(!brief?.briefFingerprint)throw new Error('brief fingerprint required');return{schemaVersion:'1.0',requestId:brief.requestId,requestVersion:brief.requestVersion,briefFingerprint:brief.briefFingerprint,reviewFingerprint:review?.auditFingerprint??null,status:brief.status,evidenceBoundary:brief.evidenceBoundary,requiresHumanApproval:true,autoOutreach:false,autoCrmWrite:false,createdAt:'2026-01-15T00:00:00Z',manifestFingerprint:hash({briefFingerprint:brief.briefFingerprint,reviewFingerprint:review?.auditFingerprint??null})};}
