import test from 'node:test';
import assert from 'node:assert/strict';
import {createContentServer} from '../src/server.mjs';

async function withServer(fn){const server=createContentServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await fn(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
const signal={sourceEventId:'a1',sourceType:'audience_question',title:'n8n retries',text:'How should retries work?',observedAt:'2026-08-20T10:00:00Z',evidenceType:'simulated'};
test('health reports deterministic zero-paid mode',()=>withServer(async base=>{const response=await fetch(`${base}/health`);assert.equal(response.status,200);assert.deepEqual(await response.json(),{status:'ok',mode:'deterministic-local',paidApis:false});}));
test('signal endpoint validates and returns evidence identity',()=>withServer(async base=>{const response=await fetch(`${base}/v1/signals`,{method:'POST',body:JSON.stringify(signal)});const body=await response.json();assert.equal(response.status,200);assert.equal(body.evidenceBoundary,'simulated');assert.equal(body.idempotencyKey.length,64);}));
test('score endpoint creates explainable topic result',()=>withServer(async base=>{const response=await fetch(`${base}/v1/topics/score`,{method:'POST',body:JSON.stringify({candidates:[{title:'n8n retry guide',evidenceIds:['a1'],businessAlignment:15}],evidence:[signal],brandPolicy:{allowedThemes:['n8n']}})});const body=await response.json();assert.equal(response.status,200);assert.equal(body.model,'deterministic-v1');assert.equal(body.topics.length,1);assert.ok(body.topics[0].score.total>0);}));
test('approval endpoint rejects unauthorized reviewer',()=>withServer(async base=>{const response=await fetch(`${base}/v1/topics/transition`,{method:'POST',body:JSON.stringify({topic:{status:'needs_review'},to:'approved',actor:'writer',role:'writer'})});assert.equal(response.status,400);assert.match((await response.json()).error,/reviewer/);}));
test('performance endpoint rejects inflated impossible funnel',()=>withServer(async base=>{const response=await fetch(`${base}/v1/performance`,{method:'POST',body:JSON.stringify({topicId:'t',channel:'blog',eventId:'e',impressions:10,clicks:20})});assert.equal(response.status,400);}));
test('metrics expose counters',()=>withServer(async base=>{await fetch(`${base}/v1/signals`,{method:'POST',body:JSON.stringify(signal)});const text=await (await fetch(`${base}/metrics`)).text();assert.match(text,/content_intelligence_signals_total/);}));
test('delivery mock exposes retry and DLQ paths',()=>withServer(async base=>{let r=await fetch(`${base}/v1/deliver`,{method:'POST',body:JSON.stringify({simulate:'rate_limit',attempt:1})});assert.equal(r.status,429);assert.equal((await r.json()).outcome,'retry');r=await fetch(`${base}/v1/deliver`,{method:'POST',body:JSON.stringify({simulate:'permanent_failure',attempt:1})});assert.equal((await r.json()).outcome,'dlq');}));
