import test from'node:test';import assert from'node:assert/strict';import{once}from'node:events';import{readFile}from'node:fs/promises';import{createServer}from'../src/server.mjs';const fixture=JSON.parse(await readFile(new URL('../examples/synthetic-service-incident.json',import.meta.url)));async function withServer(run){const s=createServer().listen(0);await once(s,'listening');try{return await run(`http://127.0.0.1:${s.address().port}`)}finally{s.close();await once(s,'close')}}
test('health reports deterministic nonexecution mode',()=>withServer(async b=>{const x=await(await fetch(`${b}/health`)).json();assert.equal(x.mode,'deterministic-local');assert.equal(x.autoExecute,false)}));
test('triage returns SEV2 plan',()=>withServer(async b=>{const r=await fetch(`${b}/triage`,{method:'POST',body:JSON.stringify(fixture)}),x=await r.json();assert.equal(r.status,200);assert.equal(x.plan.severity,'SEV2');assert.equal(x.plan.autoExecute,false)}));
test('action approval records no execution authority',()=>withServer(async b=>{const p=(await(await fetch(`${b}/triage`,{method:'POST',body:JSON.stringify(fixture)})).json()).plan,a=p.actions.find(x=>x.actionType==='page_oncall');const x=await(await fetch(`${b}/approve-action`,{method:'POST',body:JSON.stringify({plan:p,actionId:a.actionId,review:{reviewerId:'c1',reviewerRole:'incident_commander',decision:'approve',rationale:'checked'}})})).json();assert.equal(x.executionAuthorized,false)}));
test('timeline endpoint appends event',()=>withServer(async b=>{const x=await(await fetch(`${b}/timeline`,{method:'POST',body:JSON.stringify({timeline:[],event:fixture.timelineEvents[0]})})).json();assert.equal(x.timeline.length,1)}));
test('status endpoint returns unpublished draft',()=>withServer(async b=>{const severity={severity:'SEV2'};const x=await(await fetch(`${b}/status-draft`,{method:'POST',body:JSON.stringify({incident:fixture.incident,severity})})).json();assert.equal(x.published,false)}));
test('retry endpoint sends exhausted job to dlq',()=>withServer(async b=>{const x=await(await fetch(`${b}/retry`,{method:'POST',body:JSON.stringify({jobId:'j1',attempts:3,maxAttempts:3})})).json();assert.equal(x.action,'dlq')}));
test('invalid triage returns 400',()=>withServer(async b=>assert.equal((await fetch(`${b}/triage`,{method:'POST',body:'{}'})).status,400)));
test('unknown route returns 404',()=>withServer(async b=>assert.equal((await fetch(`${b}/missing`)).status,404)));
