import {createHash} from 'node:crypto';
const clean=v=>String(v??'').trim();
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const hash=v=>createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const INJECTION=/(ignore (all|previous) instructions|reveal (the )?(system|developer) prompt|act as system|override policy)/i;
const SECRET=/(api[_ -]?key\s*[:=]|password\s*[:=]|-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----)/i;
const CARD=/\b(?:\d[ -]*?){13,19}\b/;
const EMAIL=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;
const CHANNELS=new Set(['linkedin','x','instagram','email']);
const CURRENCIES=new Set(['CAD','USD','EUR','GBP']);
const AGENTS=new Set(['strategy_agent','audience_agent','creative_agent','channel_agent','compliance_agent','measurement_agent','coordinator_agent']);
const TOOLS=new Set(['brief_read','evidence_read','plan_write','asset_draft','policy_check','budget_compute','handoff_write','audit_write']);
const EVIDENCE_TYPES=new Set(['approved_product_fact','brand_guide','customer_research','legal_disclosure','performance_baseline','approved_copy']);
const LIMITS={linkedin:3000,x:280,instagram:2200,email:5000};

export function scanText(value){const t=clean(value),out=[];if(INJECTION.test(t))out.push({code:'prompt_injection',severity:'block'});if(SECRET.test(t))out.push({code:'exposed_secret',severity:'block'});if(CARD.test(t))out.push({code:'payment_card_like',severity:'block'});if(EMAIL.test(t))out.push({code:'email_like_pii',severity:'block'});return out;}
export function normalizeEvidence(raw){for(const k of['evidenceId','type','sourceUrl','observedAt','status'])if(!clean(raw?.[k]))throw new Error(`missing evidence ${k}`);if(!EVIDENCE_TYPES.has(raw.type))throw new Error('unsupported evidence type');if(!['approved','unverified','expired'].includes(raw.status))throw new Error('invalid evidence status');let url;try{url=new URL(raw.sourceUrl);}catch{throw new Error('invalid evidence URL');}if(url.protocol!=='https:')throw new Error('evidence requires https');const date=new Date(raw.observedAt);if(Number.isNaN(date.valueOf()))throw new Error('invalid evidence date');const confidence=Number(raw.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new Error('invalid evidence confidence');if(scanText(`${raw.summary??''} ${raw.excerpt??''}`).length)throw new Error('unsafe evidence content');const row={evidenceId:clean(raw.evidenceId),type:raw.type,sourceUrl:url.toString(),observedAt:date.toISOString(),status:raw.status,confidence,locale:clean(raw.locale||'en'),summary:clean(raw.summary),synthetic:raw.synthetic===true};return{...row,evidenceFingerprint:hash(row)};}
export function normalizeBrief(raw){for(const k of['campaignId','version','name','goal','ownerId','audience','locale','currency','budgetMinor','startsAt','endsAt','brandPolicyVersion'])if(raw?.[k]===undefined||clean(raw[k])==='')throw new Error(`missing ${k}`);if(!CURRENCIES.has(raw.currency))throw new Error('unsupported currency');const budgetMinor=Number(raw.budgetMinor);if(!Number.isSafeInteger(budgetMinor)||budgetMinor<1)throw new Error('invalid budgetMinor');const startsAt=new Date(raw.startsAt),endsAt=new Date(raw.endsAt);if(Number.isNaN(startsAt.valueOf())||Number.isNaN(endsAt.valueOf())||endsAt<=startsAt)throw new Error('invalid campaign window');const channels=[...new Set((raw.channels??[]).map(clean))].sort();if(!channels.length||channels.some(c=>!CHANNELS.has(c)))throw new Error('invalid channels');const kpis=[...new Set((raw.kpis??[]).map(clean).filter(Boolean))].sort();if(!kpis.length)throw new Error('kpis required');if(scanText(`${raw.name} ${raw.goal} ${raw.audience} ${raw.message??''} ${raw.callToAction??''}`).length)throw new Error('unsafe brief input');if(!Array.isArray(raw.sourceAssets)||!raw.sourceAssets.length)throw new Error('sourceAssets required');const sourceAssets=raw.sourceAssets.map(normalizeEvidence);const ids=new Set();for(const e of sourceAssets){if(ids.has(e.evidenceId))throw new Error('duplicate evidenceId');ids.add(e.evidenceId);}return{campaignId:clean(raw.campaignId),version:clean(raw.version),name:clean(raw.name),goal:clean(raw.goal),ownerId:clean(raw.ownerId),audience:clean(raw.audience),locale:clean(raw.locale).toLowerCase(),currency:raw.currency,budgetMinor,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),brandPolicyVersion:clean(raw.brandPolicyVersion),channels,kpis,message:clean(raw.message),callToAction:clean(raw.callToAction),highRisk:raw.highRisk===true,regulated:raw.regulated===true,sourceAssets,evidenceBoundary:clean(raw.evidenceBoundary||'simulated'),maxAgentSteps:Number(raw.maxAgentSteps??10),maxToolCalls:Number(raw.maxToolCalls??16)};}
export function briefFingerprint(raw){return hash(normalizeBrief(raw));}
export function buildWorkGraph(raw){const b=normalizeBrief(raw);const steps=[
{stepId:'s1',agent:'strategy_agent',tool:'brief_read',dependsOn:[],objective:'Validate campaign goal, constraints, and evidence.'},
{stepId:'s2',agent:'audience_agent',tool:'evidence_read',dependsOn:['s1'],objective:'Create an aggregate audience hypothesis without personal targeting.'},
{stepId:'s3',agent:'measurement_agent',tool:'plan_write',dependsOn:['s1'],objective:'Define KPIs, guardrails, and an observational evidence boundary.'},
{stepId:'s4',agent:'creative_agent',tool:'asset_draft',dependsOn:['s1','s2'],objective:'Draft channel assets only from approved source facts.'},
{stepId:'s5',agent:'channel_agent',tool:'plan_write',dependsOn:['s2','s4'],objective:'Propose channel timing and limits without publishing.'},
{stepId:'s6',agent:'compliance_agent',tool:'policy_check',dependsOn:['s4'],objective:'Check claims, disclosures, brand policy, and unsafe text.'},
{stepId:'s7',agent:'measurement_agent',tool:'budget_compute',dependsOn:['s3','s5'],objective:'Allocate integer-money planning budget without authorizing spend.'},
{stepId:'s8',agent:'coordinator_agent',tool:'plan_write',dependsOn:['s5','s6','s7'],objective:'Resolve bounded conflicts and assemble a review packet.'},
{stepId:'s9',agent:'coordinator_agent',tool:'handoff_write',dependsOn:['s8'],objective:'Prepare Project 09 and Project 10 handoffs after human approval.'},
{stepId:'s10',agent:'coordinator_agent',tool:'audit_write',dependsOn:['s9'],objective:'Record fingerprints and non-publishing authority boundaries.'}
];const graph={campaignId:b.campaignId,campaignVersion:b.version,steps,maxAgentSteps:b.maxAgentSteps,maxToolCalls:b.maxToolCalls,allowedAgents:[...AGENTS].sort(),allowedTools:[...TOOLS].sort(),autoPublish:false,spendAuthorized:false,graphFingerprint:hash({campaignId:b.campaignId,version:b.version,steps})};validateWorkGraph(graph);return graph;}
export function validateWorkGraph(graph){if(!Array.isArray(graph?.steps)||!graph.steps.length)throw new Error('work graph required');if(!Number.isInteger(graph.maxAgentSteps)||graph.maxAgentSteps<graph.steps.length||graph.maxAgentSteps>12)throw new Error('agent step budget exceeded');if(!Number.isInteger(graph.maxToolCalls)||graph.maxToolCalls<graph.steps.length||graph.maxToolCalls>20)throw new Error('tool call budget exceeded');const ids=new Set(graph.steps.map(s=>s.stepId));if(ids.size!==graph.steps.length)throw new Error('duplicate stepId');for(const s of graph.steps){if(!AGENTS.has(s.agent))throw new Error('unapproved agent');if(!TOOLS.has(s.tool))throw new Error('unapproved tool');if(scanText(s.objective).length)throw new Error('unsafe objective');for(const d of s.dependsOn??[])if(!ids.has(d))throw new Error('unknown dependency');}const visiting=new Set(),done=new Set(),byId=new Map(graph.steps.map(s=>[s.stepId,s]));function visit(id){if(visiting.has(id))throw new Error('cyclic dependency');if(done.has(id))return;visiting.add(id);for(const d of byId.get(id).dependsOn??[])visit(d);visiting.delete(id);done.add(id);}for(const id of ids)visit(id);return{valid:true,steps:graph.steps.length,autoPublish:false};}
export function validateClaims(raw,claims=[]){const b=normalizeBrief(raw),evidence=new Map(b.sourceAssets.map(e=>[e.evidenceId,e])),findings=[];for(const claim of claims){if(!clean(claim.claimId)||!clean(claim.text))throw new Error('invalid claim');if(scanText(claim.text).length)findings.push({claimId:claim.claimId,code:'unsafe_claim',severity:'block'});if(!Array.isArray(claim.evidenceIds)||!claim.evidenceIds.length)findings.push({claimId:claim.claimId,code:'missing_evidence',severity:'block'});else for(const id of claim.evidenceIds){const e=evidence.get(id);if(!e)findings.push({claimId:claim.claimId,code:'unknown_evidence',severity:'block',evidenceId:id});else if(e.status!=='approved'||e.confidence<.7)findings.push({claimId:claim.claimId,code:'unapproved_evidence',severity:'block',evidenceId:id});}}return{valid:!findings.some(f=>f.severity==='block'),findings,claimsChecked:claims.length,evidenceBoundary:b.evidenceBoundary};}
export function allocateBudget(raw,weights={}){const b=normalizeBrief(raw),channels=b.channels,defaultWeight=1/channels.length;let totalWeight=0;for(const c of channels){const w=Number(weights[c]??defaultWeight);if(!Number.isFinite(w)||w<0)throw new Error('invalid channel weight');totalWeight+=w;}if(totalWeight<=0)throw new Error('channel weights required');const planningCap=Math.floor(b.budgetMinor*.9),allocations=[];let used=0;channels.forEach((c,i)=>{const amount=i===channels.length-1?planningCap-used:Math.floor(planningCap*Number(weights[c]??defaultWeight)/totalWeight);used+=amount;allocations.push({channel:c,plannedMinor:amount});});return{campaignId:b.campaignId,currency:b.currency,budgetMinor:b.budgetMinor,planningCapMinor:planningCap,reserveMinor:b.budgetMinor-planningCap,allocations,totalPlannedMinor:used,spendAuthorized:false,autoSpend:false,budgetFingerprint:hash({campaignId:b.campaignId,allocations,reserveMinor:b.budgetMinor-planningCap})};}
function approvedLocaleCopy(b){return b.sourceAssets.some(e=>e.type==='approved_copy'&&e.status==='approved'&&e.locale===b.locale&&e.confidence>=.7);}
export function draftAssets(raw,claims=[]){const b=normalizeBrief(raw),claimCheck=validateClaims(b,claims);if(!claimCheck.valid)throw new Error('claim gate blocked');if(b.locale!=='en'&&!approvedLocaleCopy(b))return{campaignId:b.campaignId,status:'needs_translation',locale:b.locale,assets:[],autoTranslate:false,autoPublish:false};const base=`${b.message} ${b.callToAction}`.trim();if(!base)throw new Error('approved message and callToAction required');const assets=b.channels.map(channel=>{const text=channel==='email'?`Subject: ${b.name}\n${base}`:base;if(text.length>LIMITS[channel])throw new Error(`channel limit exceeded: ${channel}`);const asset={assetId:`${b.campaignId}-${channel}-v1`,campaignId:b.campaignId,campaignVersion:b.version,channel,locale:b.locale,text,claimIds:claims.map(c=>c.claimId).sort(),status:'draft_review_required',brandPolicyVersion:b.brandPolicyVersion,characterCount:text.length,characterLimit:LIMITS[channel],synthetic:b.evidenceBoundary==='simulated',autoPublish:false};return{...asset,assetFingerprint:hash(asset)};});return{campaignId:b.campaignId,status:'asset_review_required',locale:b.locale,assets,autoTranslate:false,autoPublish:false,draftSetFingerprint:hash(assets)};}
export function reviewAsset(raw,asset,review){const b=normalizeBrief(raw);if(!asset?.assetFingerprint||asset.campaignId!==b.campaignId||asset.campaignVersion!==b.version)throw new Error('asset scope mismatch');for(const k of['reviewerId','reviewerRole','decision','rationale','reviewedAt'])if(!clean(review?.[k]))throw new Error(`missing review ${k}`);const roles=['marketing_owner','brand_reviewer','compliance_reviewer'];if(!roles.includes(review.reviewerRole))throw new Error('unauthorized reviewer role');if(!['approve','reject','request_changes'].includes(review.decision))throw new Error('invalid review decision');const row={assetFingerprint:asset.assetFingerprint,reviewerId:clean(review.reviewerId),reviewerRole:review.reviewerRole,decision:review.decision,rationale:clean(review.rationale),reviewedAt:new Date(review.reviewedAt).toISOString(),publishingAuthorized:false,spendAuthorized:false};return{...row,reviewFingerprint:hash(row)};}
export function requiredReviewRoles(raw){const b=normalizeBrief(raw);return b.highRisk||b.regulated?['marketing_owner','brand_reviewer','compliance_reviewer']:['marketing_owner','brand_reviewer'];}
export function buildCampaignPacket(raw,graph,drafts,budget,reviews=[]){const b=normalizeBrief(raw);if(!graph?.graphFingerprint||!drafts?.draftSetFingerprint||!budget?.budgetFingerprint)throw new Error('campaign artifacts required');const required=requiredReviewRoles(b);for(const asset of drafts.assets){const approved=new Set(reviews.filter(r=>r.assetFingerprint===asset.assetFingerprint&&r.decision==='approve').map(r=>r.reviewerRole));const missing=required.filter(role=>!approved.has(role));if(missing.length)throw new Error(`missing asset approvals: ${asset.assetId}:${missing.join(',')}`);}const packet={campaignId:b.campaignId,campaignVersion:b.version,graphFingerprint:graph.graphFingerprint,draftSetFingerprint:drafts.draftSetFingerprint,budgetFingerprint:budget.budgetFingerprint,assetFingerprints:drafts.assets.map(a=>a.assetFingerprint).sort(),approvedRoles:[...new Set(reviews.map(r=>r.reviewerRole))].sort(),status:'ready_for_handoff_review',publishingAuthorized:false,spendAuthorized:false,autoPublish:false,evidenceBoundary:b.evidenceBoundary};return{...packet,packetFingerprint:hash(packet)};}
export function buildPublishingHandoff(raw,packet,drafts){const b=normalizeBrief(raw);if(!packet?.packetFingerprint||packet.campaignId!==b.campaignId)throw new Error('approved campaign packet required');const h={targetProject:'09-social-publishing-governance-system',campaignId:b.campaignId,campaignVersion:b.version,packetFingerprint:packet.packetFingerprint,assets:drafts.assets.map(a=>({assetId:a.assetId,assetFingerprint:a.assetFingerprint,channel:a.channel,locale:a.locale})),status:'ready_for_project_09_review',requiresProject09PolicyValidation:true,publishingAuthorized:false,autoPublish:false,scheduled:false};return{...h,handoffFingerprint:hash(h)};}
export function buildExperimentHandoff(raw,packet){const b=normalizeBrief(raw);if(!packet?.packetFingerprint)throw new Error('campaign packet required');const h={targetProject:'10-content-experimentation-revenue-attribution',campaignId:b.campaignId,campaignVersion:b.version,packetFingerprint:packet.packetFingerprint,kpis:b.kpis,status:'experiment_design_required',assignmentConfigured:false,controlGroupConfigured:false,revenueAttributionAllowed:false,causalClaimAllowed:false};return{...h,handoffFingerprint:hash(h)};}
export function detectAgentConflicts(proposals=[]){const findings=[];const byTopic=new Map();for(const p of proposals){if(!clean(p.agent)||!clean(p.topic)||!clean(p.value))throw new Error('invalid proposal');if(!AGENTS.has(p.agent))throw new Error('unapproved proposal agent');const prior=byTopic.get(p.topic);if(prior&&prior.value!==p.value)findings.push({code:'contradictory_proposals',topic:p.topic,agents:[prior.agent,p.agent].sort(),severity:'review'});else byTopic.set(p.topic,p);}return{requiresReview:findings.length>0,findings,consensusDoesNotOverridePolicy:true};}
export function recordOutcome(packet,outcome){if(!packet?.packetFingerprint)throw new Error('campaign packet required');for(const k of['outcomeId','metric','value','observedAt'])if(outcome?.[k]===undefined||clean(outcome[k])==='')throw new Error(`missing outcome ${k}`);const value=Number(outcome.value);if(!Number.isFinite(value))throw new Error('invalid outcome value');const row={outcomeId:clean(outcome.outcomeId),packetFingerprint:packet.packetFingerprint,metric:clean(outcome.metric),value,observedAt:new Date(outcome.observedAt).toISOString(),providerVerified:outcome.providerVerified===true,causalClaimAllowed:false,revenueAttributionAllowed:false,attributionBoundary:'observational_until_project_10_validates_experiment'};return{...row,outcomeFingerprint:hash(row)};}
export function appendAudit(events,event){for(const k of['eventId','campaignId','type','actorId','actorRole','occurredAt','summary'])if(!clean(event?.[k]))throw new Error(`missing audit ${k}`);if((events??[]).some(e=>e.eventId===event.eventId))throw new Error('duplicate audit event');const at=new Date(event.occurredAt);if(Number.isNaN(at.valueOf()))throw new Error('invalid audit date');if(events?.length&&at<new Date(events.at(-1).occurredAt))throw new Error('audit out of order');const previousHash=events?.at(-1)?.eventHash??'GENESIS';const row={eventId:clean(event.eventId),campaignId:clean(event.campaignId),type:clean(event.type),actorId:clean(event.actorId),actorRole:clean(event.actorRole),occurredAt:at.toISOString(),summary:clean(event.summary),artifactFingerprints:[...new Set((event.artifactFingerprints??[]).map(clean))].sort(),previousHash};return[...(events??[]),{...row,eventHash:hash(row)}];}
export function verifyAudit(events){let previous='GENESIS';for(const e of events??[]){const{eventHash,...row}=e;if(row.previousHash!==previous||hash(row)!==eventHash)return{valid:false,brokenAt:e.eventId};previous=eventHash;}return{valid:true,events:events?.length??0,headHash:previous};}
export function nextRetry(job){const attempts=Number(job?.attempts??0),maxAttempts=Number(job?.maxAttempts??3);if(!Number.isInteger(attempts)||!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>5)throw new Error('invalid retry policy');if(attempts>=maxAttempts)return{jobId:clean(job.jobId),action:'dlq',attempts,maxAttempts,reason:clean(job.lastError),autoReplay:false};return{jobId:clean(job.jobId),action:'retry',attempts:attempts+1,maxAttempts,delaySeconds:Math.min(300,20*2**attempts)};}
export function buildManifest(raw,graph,drafts,budget,packet,audit,publishingHandoff=null,experimentHandoff=null){const b=normalizeBrief(raw);if(!graph?.graphFingerprint||!drafts?.draftSetFingerprint||!budget?.budgetFingerprint||!packet?.packetFingerprint)throw new Error('required campaign artifacts missing');const verified=verifyAudit(audit);if(!verified.valid)throw new Error('invalid audit chain');const m={schemaVersion:'1.0',campaignId:b.campaignId,campaignVersion:b.version,briefFingerprint:briefFingerprint(b),graphFingerprint:graph.graphFingerprint,draftSetFingerprint:drafts.draftSetFingerprint,budgetFingerprint:budget.budgetFingerprint,packetFingerprint:packet.packetFingerprint,auditHeadHash:verified.headHash,publishingHandoffFingerprint:publishingHandoff?.handoffFingerprint??null,experimentHandoffFingerprint:experimentHandoff?.handoffFingerprint??null,evidenceBoundary:b.evidenceBoundary,requiresHumanApproval:true,publishingAuthorized:false,spendAuthorized:false,autoPublish:false,causalClaimAllowed:false,revenueAttributionAllowed:false,createdAt:b.startsAt};return{...m,manifestFingerprint:hash(m)};}
