import{createHash}from'node:crypto';
const FORMATS=new Set(['article','reel_script','carousel','email','short_video_script']);
const EVIDENCE=new Set(['simulated','source_verified']);
const KINDS=new Set(['factual','opinion','instruction']);
const INJECTION=/ignore (?:all |the )?(?:previous|prior) instructions|system prompt|developer message|reveal.*prompt|act as/i;
const SENSITIVE=/\b(medical|legal|financial advice|investment|guarantee|guaranteed|cure|diagnos(?:e|is)|zero risk)\b/i;
const PII=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b|(?:\+?\d[\d\s().-]{7,}\d)/i;
const clean=x=>String(x??'').replace(/\s+/g,' ').trim();
const sha=x=>createHash('sha256').update(x).digest('hex');
const words=x=>clean(x).split(/\s+/).filter(Boolean).length;
const unique=x=>[...new Set(x)];
export function normalizeBrandMemory(input){if(!input||typeof input!=='object')throw new Error('brand memory required');for(const k of['brandId','version','name','audience'])if(input[k]===undefined||clean(input[k])==='')throw new Error(`missing brand ${k}`);if(!Number.isInteger(Number(input.version))||Number(input.version)<1)throw new Error('invalid brand version');return{brandId:clean(input.brandId),version:Number(input.version),name:clean(input.name),audience:clean(input.audience),tone:unique((input.tone??[]).map(clean).filter(Boolean)),allowedCtas:unique((input.allowedCtas??[]).map(clean).filter(Boolean)),prohibitedPhrases:unique((input.prohibitedPhrases??[]).map(clean).filter(Boolean)),requiredDisclosures:unique((input.requiredDisclosures??[]).map(clean).filter(Boolean)),readingLevel:clean(input.readingLevel||'general')}}
export function normalizeBrief(input){if(!input||typeof input!=='object')throw new Error('content brief required');for(const k of['sourceEventId','campaignId','topicId','title','audience','objective','formats','evidence','claims','brandVersion'])if(input[k]===undefined||input[k]==='')throw new Error(`missing ${k}`);if(!Array.isArray(input.formats)||!input.formats.length||new Set(input.formats).size!==input.formats.length||input.formats.some(x=>!FORMATS.has(x)))throw new Error('invalid formats');if(!Array.isArray(input.evidence)||!input.evidence.length||input.evidence.length>50)throw new Error('evidence required');const evidence=input.evidence.map((x,i)=>{for(const k of['evidenceId','title','summary','evidenceType'])if(!clean(x[k]))throw new Error(`evidence ${i} missing ${k}`);if(!EVIDENCE.has(x.evidenceType))throw new Error('invalid evidence type');if(x.sourceUrl){let u;try{u=new URL(x.sourceUrl)}catch{throw new Error('invalid evidence URL')}if(!['http:','https:'].includes(u.protocol))throw new Error('unsafe evidence URL')}return{evidenceId:clean(x.evidenceId),title:clean(x.title).slice(0,300),summary:clean(x.summary).slice(0,2000),sourceUrl:clean(x.sourceUrl),evidenceType:x.evidenceType}});if(new Set(evidence.map(x=>x.evidenceId)).size!==evidence.length)throw new Error('duplicate evidence identity');if(!Array.isArray(input.claims)||input.claims.length>50)throw new Error('invalid claims');const claims=input.claims.map((x,i)=>{for(const k of['claimId','text','kind','evidenceIds'])if(x[k]===undefined||x[k]==='')throw new Error(`claim ${i} missing ${k}`);if(!KINDS.has(x.kind)||!Array.isArray(x.evidenceIds))throw new Error('invalid claim');return{claimId:clean(x.claimId),text:clean(x.text).slice(0,500),kind:x.kind,evidenceIds:unique(x.evidenceIds.map(clean).filter(Boolean))}});if(new Set(claims.map(x=>x.claimId)).size!==claims.length)throw new Error('duplicate claim identity');const brandVersion=Number(input.brandVersion);if(!Number.isInteger(brandVersion)||brandVersion<1)throw new Error('invalid brand version');return{schemaVersion:'1.0',sourceEventId:clean(input.sourceEventId),campaignId:clean(input.campaignId),topicId:clean(input.topicId),title:clean(input.title).slice(0,200),audience:clean(input.audience).slice(0,200),objective:clean(input.objective).slice(0,500),formats:[...input.formats],evidence,claims,brandVersion,cta:clean(input.cta),requestedBy:clean(input.requestedBy||'system')}}
export const briefKey=brief=>sha(`brief:${brief.sourceEventId}`);
export const packageKey=(brief,version)=>sha(`${brief.campaignId}:${brief.topicId}:${brief.brandVersion}:${version}`);
export function validateClaims(brief){const ids=new Set(brief.evidence.map(x=>x.evidenceId));const evidenceFindings=brief.evidence.flatMap(e=>INJECTION.test(`${e.title} ${e.summary}`)?[{code:'prompt_injection_evidence',evidenceId:e.evidenceId,severity:'error'}]:[]);const claimFindings=brief.claims.flatMap(c=>{const missing=c.evidenceIds.filter(id=>!ids.has(id));const findings=[];if(c.kind==='factual'&&!c.evidenceIds.length)findings.push({code:'unsupported_factual_claim',claimId:c.claimId,severity:'error'});if(missing.length)findings.push({code:'unknown_evidence_reference',claimId:c.claimId,severity:'error',missing});if(INJECTION.test(c.text))findings.push({code:'prompt_injection_text',claimId:c.claimId,severity:'error'});if(SENSITIVE.test(c.text))findings.push({code:'sensitive_claim',claimId:c.claimId,severity:'review'});return findings});return[...evidenceFindings,...claimFindings]}
function claimLines(brief){return brief.claims.map(c=>({claimId:c.claimId,text:c.text,evidenceIds:c.evidenceIds,kind:c.kind}))}
export function buildVisualBrief(brief){return{style:'clean editorial system diagram',palette:['navy','blue','teal'],requiredAssets:brief.formats.filter(x=>['carousel','reel_script','short_video_script'].includes(x)).map(format=>({format,assetType:format==='carousel'?'slide-set':'shot-list',altText:`Visual explanation for ${brief.title}`})),prohibited:['unlicensed logos','unverified screenshots','misleading before-after imagery']}}
export function producePackage(briefInput,brandInput,version=1){const brief=normalizeBrief(briefInput),brand=normalizeBrandMemory(brandInput);if(brief.brandVersion!==brand.version)throw new Error('brand version mismatch');if(!Number.isInteger(version)||version<1)throw new Error('invalid package version');const primary=brief.claims[0]?.text||brief.objective,cta=brief.cta||brand.allowedCtas[0]||'learn more',disclosure=brand.requiredDisclosures.join('; '),evidenceSummary=brief.evidence.map(x=>x.summary).join(' ');const variants={};if(brief.formats.includes('article'))variants.article={headline:brief.title,dek:brief.objective,sections:[{heading:'Why it matters',body:`For ${brief.audience}: ${primary}`},{heading:'Evidence',body:evidenceSummary},{heading:'Practical next step',body:cta}],claims:claimLines(brief),disclosure,wordCount:words(`${brief.title} ${brief.objective} ${primary} ${evidenceSummary} ${cta}`)};if(brief.formats.includes('reel_script'))variants.reel_script={hook:brief.title,estimatedSeconds:45,scenes:[{second:0,visual:'title card',voiceover:brief.objective},{second:8,visual:'evidence card',voiceover:primary},{second:32,visual:'workflow diagram',voiceover:evidenceSummary.slice(0,280)},{second:41,visual:'call to action',voiceover:cta}],caption:`${brief.title}. ${disclosure}`.trim(),claims:claimLines(brief)};if(brief.formats.includes('carousel'))variants.carousel={slides:[{number:1,headline:brief.title,body:brief.objective,altText:`Cover: ${brief.title}`},{number:2,headline:'Core evidence',body:primary,altText:`Evidence for ${brief.title}`},{number:3,headline:'How it works',body:evidenceSummary.slice(0,300),altText:`Process for ${brief.title}`},{number:4,headline:'Next step',body:cta,altText:`Call to action: ${cta}`}],claims:claimLines(brief)};if(brief.formats.includes('email'))variants.email={subject:brief.title.slice(0,60),preheader:brief.objective.slice(0,100),body:`${brief.objective}\n\n${primary}\n\n${evidenceSummary}\n\n${cta}`,cta,claims:claimLines(brief),disclosure};if(brief.formats.includes('short_video_script'))variants.short_video_script={title:brief.title,estimatedSeconds:75,shots:[{id:1,duration:8,visual:'problem statement',voiceover:brief.objective,onScreenText:brief.title},{id:2,duration:22,visual:'evidence highlights',voiceover:primary,onScreenText:'Evidence first'},{id:3,duration:30,visual:'system walkthrough',voiceover:evidenceSummary.slice(0,350),onScreenText:'Controlled workflow'},{id:4,duration:15,visual:'next step',voiceover:cta,onScreenText:cta}],claims:claimLines(brief),disclosure};const base={packageId:packageKey(brief,version),version,status:'generated',briefIdentity:briefKey(brief),campaignId:brief.campaignId,topicId:brief.topicId,brand:{brandId:brand.brandId,version:brand.version},formats:brief.formats,variants,visualBrief:buildVisualBrief(brief),generatedBy:'deterministic-template-v1',evidenceBoundary:'simulated-output'};return{...base,fingerprint:sha(JSON.stringify(base))}}
export function qualityGate(pkg,briefInput,brandInput){const brief=normalizeBrief(briefInput),brand=normalizeBrandMemory(brandInput),findings=[...validateClaims(brief)];const text=JSON.stringify(pkg.variants);for(const phrase of brand.prohibitedPhrases)if(text.toLowerCase().includes(phrase.toLowerCase()))findings.push({code:'prohibited_brand_phrase',severity:'error',phrase});if(INJECTION.test(text))findings.push({code:'prompt_injection_output',severity:'error'});if(PII.test(text))findings.push({code:'pii_detected',severity:'error'});for(const format of brief.formats)if(!pkg.variants[format])findings.push({code:'missing_format',severity:'error',format});if(pkg.variants.email&&pkg.variants.email.subject.length>60)findings.push({code:'email_subject_too_long',severity:'error'});if(pkg.variants.carousel){if(pkg.variants.carousel.slides.length<4||pkg.variants.carousel.slides.length>10)findings.push({code:'carousel_slide_count',severity:'error'});for(const slide of pkg.variants.carousel.slides)if(!clean(slide.altText))findings.push({code:'missing_alt_text',severity:'error',slide:slide.number})}for(const format of ['reel_script','short_video_script'])if(pkg.variants[format]&&pkg.variants[format].estimatedSeconds>90)findings.push({code:'duration_too_long',severity:'error',format});const ctas=Object.values(pkg.variants).flatMap(v=>[v.cta,...(v.slides??[]).filter(x=>x.headline==='Next step').map(x=>x.body)]).filter(Boolean);if(unique(ctas).length>1)findings.push({code:'inconsistent_cta',severity:'review'});const requiredRoles=['brand_reviewer','factual_reviewer'];if(findings.some(x=>x.code==='sensitive_claim'))requiredRoles.push('legal_reviewer');const errors=findings.filter(x=>x.severity==='error').length;return{passed:errors===0,decision:errors?'qa_failed':'needs_review',findings,requiredRoles:unique(requiredRoles),summary:{errors,reviews:findings.filter(x=>x.severity==='review').length,formatsChecked:brief.formats.length}}}
const transitions={generated:['qa_failed','needs_review'],qa_failed:['generated','archived'],needs_review:['approved','rejected'],approved:['export_ready','archived'],export_ready:['released'],released:[],rejected:[],archived:[]};
export function transitionPackage(pkg,to,actor,role,requiredRoles=[],approvals=[]){if(!clean(actor))throw new Error('actor required');if(!(transitions[pkg.status]??[]).includes(to))throw new Error(`invalid transition ${pkg.status}->${to}`);if(['approved','rejected'].includes(to)&&!['brand_reviewer','factual_reviewer','legal_reviewer'].includes(role))throw new Error('reviewer role required');if(to==='approved'){const approved=new Set([...approvals,{role,status:'approved'}].filter(x=>x.status==='approved').map(x=>x.role));const missing=requiredRoles.filter(x=>!approved.has(x));if(missing.length)throw new Error(`missing approvals: ${missing.join(',')}`)}return{...pkg,status:to,lastActor:clean(actor),lastRole:clean(role)}}
export function buildExportManifest(pkg,approvals){if(pkg.status!=='approved')throw new Error('approved package required');return{packageId:pkg.packageId,version:pkg.version,fingerprint:pkg.fingerprint,brand:pkg.brand,formats:pkg.formats,approvalEvidence:approvals.map(x=>({role:x.role,actor:x.actor,status:x.status})),files:pkg.formats.map(format=>({format,path:`content/${pkg.packageId}/v${pkg.version}/${format}.json`,sha256:sha(JSON.stringify(pkg.variants[format]))})),evidenceBoundary:pkg.evidenceBoundary}}
export function classifyDelivery(status,attempt,max=3){if(status>=200&&status<300)return'delivered';if((status===429||status>=500)&&attempt<max)return'retry';return'dlq'}
export function computeKpis(events){const completed=events.filter(x=>x.type==='package_approved').length,failed=events.filter(x=>x.type==='qa_failed').length,released=events.filter(x=>x.type==='package_released'&&x.evidence==='provider_verified').length;return{packagesApproved:completed,qaFailureRate:(completed+failed)?failed/(completed+failed):0,providerVerifiedReleases:released,simulatedBusinessOutcome:false}}
