import {createHash} from 'node:crypto';

const clean=value=>String(value??'').trim();
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
const hash=value=>createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');
const INJECTION=/(ignore (all|previous) instructions|reveal (the )?(system|developer) prompt|act as system|override policy)/i;
const SECRET=/(api[_ -]?key\s*[:=]|password\s*[:=]|-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----)/i;
const CARD=/\b(?:\d[ -]*?){13,19}\b/;
const EMAIL=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;
const PHONE=/(?:\+?\d[\d ()-]{8,}\d)/;
const CHANNELS=new Set(['email','in_app','phone','none']);
const SIGNAL_TYPES=new Set(['product_usage','support','billing','relationship','survey','renewal','security']);
const SOURCES=new Set(['product_analytics','support_system','billing_system','crm','survey_system','contract_system','security_system']);
const ALLOWED_AGENTS=new Set(['signal_agent','health_agent','risk_agent','playbook_agent','compliance_agent','coordinator_agent']);
const ALLOWED_TOOLS=new Set(['signal_read','profile_read','score_compute','policy_evaluate','timeline_write','draft_generator','outcome_record']);
const REQUIRED_METRICS=['weeklyActiveDays','adoptionPercent','openCriticalTickets','paymentDaysLate','relationshipScore'];

export function scanText(value){const text=clean(value),findings=[];if(INJECTION.test(text))findings.push({code:'prompt_injection',severity:'block'});if(SECRET.test(text))findings.push({code:'exposed_secret',severity:'block'});if(CARD.test(text))findings.push({code:'payment_card_like',severity:'block'});if(EMAIL.test(text))findings.push({code:'email_like_pii',severity:'redact'});if(PHONE.test(text))findings.push({code:'phone_like_pii',severity:'redact'});return findings;}

export function normalizePolicy(raw={}){const required=['policyId','version','timezone'];for(const key of required)if(!clean(raw[key]))throw new Error(`missing policy ${key}`);const maxTouches=Number(raw.maxTouchesPer14Days??2),cooldownHours=Number(raw.cooldownHours??72),quietStart=Number(raw.quietHours?.start??20),quietEnd=Number(raw.quietHours?.end??8);if(!Number.isInteger(maxTouches)||maxTouches<1||maxTouches>5)throw new Error('invalid maxTouchesPer14Days');if(!Number.isInteger(cooldownHours)||cooldownHours<24||cooldownHours>720)throw new Error('invalid cooldownHours');for(const [key,n] of Object.entries({quietStart,quietEnd}))if(!Number.isInteger(n)||n<0||n>23)throw new Error(`invalid ${key}`);const allowedChannels=[...new Set((raw.allowedChannels??['email','in_app','phone']).map(clean))].sort();if(!allowedChannels.length||allowedChannels.some(c=>!CHANNELS.has(c)||c==='none'))throw new Error('invalid allowedChannels');return{policyId:clean(raw.policyId),version:clean(raw.version),timezone:clean(raw.timezone),maxTouchesPer14Days:maxTouches,cooldownHours,quietHours:{start:quietStart,end:quietEnd},allowedChannels,minimumEvidenceConfidence:Number(raw.minimumEvidenceConfidence??.7),requireHumanApproval:true,autoSend:false,allowDiscountOffers:false};}

export function normalizeCustomer(raw){for(const key of ['customerId','accountOwnerId','segment','region','lifecycleStage','contractRenewalAt'])if(!clean(raw?.[key]))throw new Error(`missing customer ${key}`);const renewal=new Date(raw.contractRenewalAt);if(Number.isNaN(renewal.valueOf()))throw new Error('invalid contractRenewalAt');const consent=Object.fromEntries([...CHANNELS].filter(x=>x!=='none').map(channel=>[channel,raw.channelConsent?.[channel]===true]));const text=`${raw.displayName??''} ${raw.notes??''}`;const unsafe=scanText(text).filter(x=>x.severity==='block');if(unsafe.length)throw new Error('unsafe customer input');return{customerId:clean(raw.customerId),accountOwnerId:clean(raw.accountOwnerId),segment:clean(raw.segment).toLowerCase(),region:clean(raw.region).toUpperCase(),lifecycleStage:clean(raw.lifecycleStage).toLowerCase(),contractRenewalAt:renewal.toISOString(),channelConsent:consent,legalHold:raw.legalHold===true,activeDispute:raw.activeDispute===true,paymentHardship:raw.paymentHardship===true,doNotContact:raw.doNotContact===true,synthetic:raw.synthetic===true};}

export function normalizeSignal(raw,customerId){for(const key of ['signalId','customerId','type','source','observedAt','confidence'])if(raw?.[key]===undefined||raw?.[key]===null||clean(raw[key])==='')throw new Error(`missing signal ${key}`);if(raw.customerId!==customerId)throw new Error('signal customer scope mismatch');if(!SIGNAL_TYPES.has(raw.type))throw new Error('unsupported signal type');if(!SOURCES.has(raw.source))throw new Error('unsupported signal source');const observedAt=new Date(raw.observedAt);if(Number.isNaN(observedAt.valueOf()))throw new Error('invalid signal observedAt');const confidence=Number(raw.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new Error('invalid signal confidence');const value=typeof raw.value==='boolean'?raw.value:Number(raw.value);if(typeof value!=='boolean'&&!Number.isFinite(value))throw new Error('invalid signal value');if(scanText(`${raw.summary??''} ${raw.rawText??''}`).some(x=>x.severity==='block'))throw new Error('unsafe signal content');const row={signalId:clean(raw.signalId),customerId,type:raw.type,source:raw.source,metric:clean(raw.metric),value,unit:clean(raw.unit),observedAt:observedAt.toISOString(),confidence,providerVerified:raw.providerVerified===true,synthetic:raw.synthetic===true,summary:clean(raw.summary)};return{...row,signalFingerprint:hash(row)};}

export function normalizeCase(raw){for(const key of ['caseId','caseVersion','asOf'])if(!clean(raw?.[key]))throw new Error(`missing ${key}`);const asOf=new Date(raw.asOf);if(Number.isNaN(asOf.valueOf()))throw new Error('invalid asOf');const customer=normalizeCustomer(raw.customer),policy=normalizePolicy(raw.policy);if(!Array.isArray(raw.signals)||!raw.signals.length)throw new Error('signals required');const ids=new Set();const signals=raw.signals.map(s=>{const row=normalizeSignal(s,customer.customerId);if(ids.has(row.signalId))throw new Error('duplicate signalId');ids.add(row.signalId);if(new Date(row.observedAt)>asOf)throw new Error('future signal');return row;});return{caseId:clean(raw.caseId),caseVersion:clean(raw.caseVersion),asOf:asOf.toISOString(),customer,policy,signals,previousTouches:(raw.previousTouches??[]).map(normalizeTouch),evidenceBoundary:clean(raw.evidenceBoundary||'simulated')};}

function normalizeTouch(raw){for(const key of ['touchId','channel','occurredAt'])if(!clean(raw?.[key]))throw new Error(`missing touch ${key}`);if(!CHANNELS.has(raw.channel)||raw.channel==='none')throw new Error('invalid touch channel');const occurredAt=new Date(raw.occurredAt);if(Number.isNaN(occurredAt.valueOf()))throw new Error('invalid touch occurredAt');return{touchId:clean(raw.touchId),channel:raw.channel,occurredAt:occurredAt.toISOString(),playbookId:clean(raw.playbookId)};}

export function caseFingerprint(raw){return hash(normalizeCase(raw));}

export function buildAgentPlan(raw){const data=normalizeCase(raw);const steps=[
 {stepId:'s1',agent:'signal_agent',tool:'signal_read',objective:'Validate scoped customer signals and provenance.'},
 {stepId:'s2',agent:'health_agent',tool:'score_compute',objective:'Compute a deterministic health score from verified metrics.'},
 {stepId:'s3',agent:'risk_agent',tool:'policy_evaluate',objective:'Classify risk drivers without inventing facts.'},
 {stepId:'s4',agent:'playbook_agent',tool:'policy_evaluate',objective:'Select an eligible intervention playbook.'},
 {stepId:'s5',agent:'compliance_agent',tool:'policy_evaluate',objective:'Enforce consent, suppression, frequency, cooldown, and quiet hours.'},
 {stepId:'s6',agent:'coordinator_agent',tool:'draft_generator',objective:'Draft a reviewable intervention without contacting the customer.'},
 {stepId:'s7',agent:'coordinator_agent',tool:'timeline_write',objective:'Record fingerprints and the human decision boundary.'}
];return{caseId:data.caseId,caseVersion:data.caseVersion,steps,allowedAgents:[...ALLOWED_AGENTS].sort(),allowedTools:[...ALLOWED_TOOLS].sort(),maxAgentSteps:7,maxToolCalls:10,parallelGroups:[['s2','s3'],['s4','s5']],autoSend:false,autoDiscount:false,planFingerprint:hash({caseId:data.caseId,caseVersion:data.caseVersion,steps})};}

export function validateAgentPlan(plan){if(!Array.isArray(plan?.steps)||!plan.steps.length)throw new Error('agent plan required');if(plan.steps.length>Number(plan.maxAgentSteps)||Number(plan.maxToolCalls)>10)throw new Error('agent budget exceeded');const ids=new Set();for(const step of plan.steps){if(ids.has(step.stepId))throw new Error('duplicate agent step');ids.add(step.stepId);if(!ALLOWED_AGENTS.has(step.agent))throw new Error('unapproved agent');if(!ALLOWED_TOOLS.has(step.tool))throw new Error('unapproved tool');if(scanText(step.objective).some(x=>x.severity==='block'))throw new Error('unsafe agent objective');}return{valid:true,steps:plan.steps.length,autoSend:false};}

function latestMetrics(data){const grouped=new Map();for(const signal of data.signals){if(signal.confidence<data.policy.minimumEvidenceConfidence||!signal.metric)continue;const current=grouped.get(signal.metric);if(!current||new Date(signal.observedAt)>new Date(current.observedAt))grouped.set(signal.metric,signal);}return grouped;}
function scoreMetric(metric,value){const n=Number(value);switch(metric){case'weeklyActiveDays':return Math.max(0,Math.min(100,n/5*100));case'adoptionPercent':return Math.max(0,Math.min(100,n));case'openCriticalTickets':return Math.max(0,100-Math.max(0,n)*25);case'paymentDaysLate':return Math.max(0,100-Math.max(0,n)*3);case'relationshipScore':return Math.max(0,Math.min(100,n*20));default:return null;}}

export function evaluateHealth(raw){const data=normalizeCase(raw),metrics=latestMetrics(data),weights={weeklyActiveDays:.25,adoptionPercent:.25,openCriticalTickets:.2,paymentDaysLate:.15,relationshipScore:.15},missing=REQUIRED_METRICS.filter(x=>!metrics.has(x)),components=[];for(const metric of REQUIRED_METRICS){const signal=metrics.get(metric);if(!signal)continue;const score=scoreMetric(metric,signal.value);components.push({metric,value:signal.value,score:Number(score.toFixed(2)),weight:weights[metric],weightedScore:Number((score*weights[metric]).toFixed(2)),signalId:signal.signalId,providerVerified:signal.providerVerified});}const observedWeight=components.reduce((sum,x)=>sum+x.weight,0),healthScore=observedWeight?Number((components.reduce((sum,x)=>sum+x.weightedScore,0)/observedWeight).toFixed(2)):null;let riskBand=healthScore===null?'unknown':healthScore<40?'critical':healthScore<60?'high':healthScore<75?'medium':'healthy';const daysToRenewal=Math.ceil((new Date(data.customer.contractRenewalAt)-new Date(data.asOf))/86400000);const riskDrivers=[];if(Number(metrics.get('openCriticalTickets')?.value??0)>0)riskDrivers.push('critical_support_open');if(Number(metrics.get('paymentDaysLate')?.value??0)>14)riskDrivers.push('payment_delay');if(Number(metrics.get('adoptionPercent')?.value??100)<50)riskDrivers.push('low_adoption');if(daysToRenewal>=0&&daysToRenewal<=90)riskDrivers.push('renewal_window');if(data.customer.activeDispute)riskDrivers.push('active_dispute');if(data.customer.paymentHardship)riskDrivers.push('payment_hardship');const status=missing.length>1?'insufficient_evidence':riskBand==='healthy'?'monitor':'intervention_candidate';const report={caseId:data.caseId,caseVersion:data.caseVersion,customerId:data.customer.customerId,status,healthScore,riskBand,daysToRenewal,riskDrivers,missingMetrics:missing,components,evidenceBoundary:data.evidenceBoundary,requiresHumanReview:true,notChurnPrediction:true,evaluatedAt:data.asOf};return{...report,healthFingerprint:hash(report)};}

function withinQuietHours(date,quiet){const hour=date.getUTCHours();return quiet.start>quiet.end?hour>=quiet.start||hour<quiet.end:hour>=quiet.start&&hour<quiet.end;}
export function policyGate(raw,health,channel='email'){const data=normalizeCase(raw),now=new Date(data.asOf),findings=[];if(!CHANNELS.has(channel)||channel==='none'||!data.policy.allowedChannels.includes(channel))findings.push({code:'channel_not_allowed',severity:'block'});if(!data.customer.channelConsent[channel])findings.push({code:'missing_channel_consent',severity:'block'});if(data.customer.doNotContact)findings.push({code:'do_not_contact',severity:'block'});if(data.customer.legalHold)findings.push({code:'legal_hold',severity:'block'});if(data.customer.activeDispute)findings.push({code:'active_dispute',severity:'review'});if(data.customer.paymentHardship)findings.push({code:'payment_hardship',severity:'review'});const recent=data.previousTouches.filter(t=>now-new Date(t.occurredAt)<=14*86400000&&now>=new Date(t.occurredAt));if(recent.length>=data.policy.maxTouchesPer14Days)findings.push({code:'frequency_cap',severity:'block'});const last=recent.sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt))[0];if(last&&(now-new Date(last.occurredAt))/3600000<data.policy.cooldownHours)findings.push({code:'cooldown_active',severity:'block'});if(withinQuietHours(now,data.policy.quietHours))findings.push({code:'quiet_hours',severity:'block'});if(health.status==='insufficient_evidence')findings.push({code:'insufficient_evidence',severity:'block'});if(health.riskBand==='healthy')findings.push({code:'healthy_no_intervention',severity:'block'});return{eligible:!findings.some(x=>x.severity==='block'),requiresReview:findings.some(x=>x.severity==='review')||true,channel,findings,autoSend:false,discountAllowed:false};}

export function recommendIntervention(raw,preferredChannel='email'){const data=normalizeCase(raw),health=evaluateHealth(data),gate=policyGate(data,health,preferredChannel);let playbookId='none',priority='none';if(gate.eligible){if(health.riskDrivers.includes('critical_support_open')){playbookId='service_recovery';priority='urgent';}else if(health.riskDrivers.includes('payment_hardship')){playbookId='human_finance_support';priority='high';}else if(health.riskDrivers.includes('low_adoption')){playbookId='adoption_coaching';priority='high';}else if(health.riskDrivers.includes('renewal_window')){playbookId='renewal_success_review';priority='medium';}else{playbookId='human_check_in';priority='medium';}}const recommendation={caseId:data.caseId,caseVersion:data.caseVersion,customerId:data.customer.customerId,healthFingerprint:health.healthFingerprint,playbookId,priority,channel:gate.eligible?preferredChannel:'none',status:gate.eligible?'approval_required':'blocked',rationaleDrivers:health.riskDrivers,policyFindings:gate.findings,requiresHumanApproval:true,autoSend:false,offerAuthorized:false,draft:{subject:gate.eligible?'Customer success check-in':'',bodyTemplate:gate.eligible?'A customer-success manager should review the verified drivers and personalize this draft.':''},evidenceBoundary:data.evidenceBoundary};return{...recommendation,recommendationFingerprint:hash(recommendation)};}

export function recordApproval(recommendation,approval){if(!recommendation?.recommendationFingerprint)throw new Error('recommendation required');for(const key of ['reviewerId','reviewerRole','decision','rationale','reviewedAt'])if(!clean(approval?.[key]))throw new Error(`missing approval ${key}`);if(!['customer_success_manager','support_manager','finance_reviewer','legal_reviewer'].includes(approval.reviewerRole))throw new Error('unauthorized reviewer role');if(!['approve','reject','request_changes'].includes(approval.decision))throw new Error('invalid approval decision');if(recommendation.status==='blocked'&&approval.decision==='approve')throw new Error('blocked recommendation cannot be approved');if(recommendation.playbookId==='human_finance_support'&&approval.decision==='approve'&&approval.reviewerRole!=='finance_reviewer')throw new Error('finance review required');const row={recommendationFingerprint:recommendation.recommendationFingerprint,reviewerId:clean(approval.reviewerId),reviewerRole:approval.reviewerRole,decision:approval.decision,rationale:clean(approval.rationale),reviewedAt:new Date(approval.reviewedAt).toISOString(),deliveryAuthorized:false,offerAuthorized:false};return{...row,approvalFingerprint:hash(row)};}

export function buildInterventionDraft(raw,recommendation,approval){const data=normalizeCase(raw);if(!recommendation?.recommendationFingerprint||approval?.recommendationFingerprint!==recommendation.recommendationFingerprint)throw new Error('bound approval required');if(approval.decision!=='approve')throw new Error('approved decision required');if(recommendation.status!=='approval_required')throw new Error('recommendation not eligible');const draft={caseId:data.caseId,caseVersion:data.caseVersion,customerId:data.customer.customerId,recommendationFingerprint:recommendation.recommendationFingerprint,approvalFingerprint:approval.approvalFingerprint,channel:recommendation.channel,playbookId:recommendation.playbookId,status:'mock_delivery_ready',recipientResolved:false,personalizationRequired:true,deliveryMode:'mock',deliveryAuthorized:false,sent:false,discountIncluded:false,createdAt:data.asOf};return{...draft,draftFingerprint:hash(draft)};}

export function recordOutcome(draft,outcome){if(!draft?.draftFingerprint)throw new Error('draft required');for(const key of ['outcomeId','observedAt','type'])if(!clean(outcome?.[key]))throw new Error(`missing outcome ${key}`);if(!['no_response','meeting_booked','usage_improved','ticket_resolved','renewed','churned'].includes(outcome.type))throw new Error('invalid outcome type');const row={outcomeId:clean(outcome.outcomeId),draftFingerprint:draft.draftFingerprint,observedAt:new Date(outcome.observedAt).toISOString(),type:outcome.type,providerVerified:outcome.providerVerified===true,causalClaimAllowed:false,attributionBoundary:'observational_only_without_randomized_control',notes:clean(outcome.notes)};return{...row,outcomeFingerprint:hash(row)};}

export function appendTimeline(events,event){for(const key of ['eventId','caseId','type','actorId','actorRole','occurredAt','summary'])if(!clean(event?.[key]))throw new Error(`missing timeline ${key}`);if((events??[]).some(x=>x.eventId===event.eventId))throw new Error('duplicate timeline event');const occurredAt=new Date(event.occurredAt);if(Number.isNaN(occurredAt.valueOf()))throw new Error('invalid timeline date');if(events?.length&&occurredAt<new Date(events.at(-1).occurredAt))throw new Error('timeline out of order');const previousHash=events?.at(-1)?.eventHash??'GENESIS';const row={eventId:clean(event.eventId),caseId:clean(event.caseId),type:clean(event.type),actorId:clean(event.actorId),actorRole:clean(event.actorRole),occurredAt:occurredAt.toISOString(),summary:clean(event.summary),artifactFingerprints:[...new Set((event.artifactFingerprints??[]).map(clean))].sort(),previousHash};return[...(events??[]),{...row,eventHash:hash(row)}];}
export function verifyTimeline(events){let previous='GENESIS';for(const event of events??[]){const{eventHash,...row}=event;if(row.previousHash!==previous||hash(row)!==eventHash)return{valid:false,brokenAt:event.eventId};previous=eventHash;}return{valid:true,events:events?.length??0,headHash:previous};}
export function nextRetry(job){const attempts=Number(job?.attempts??0),maxAttempts=Number(job?.maxAttempts??3);if(!Number.isInteger(attempts)||!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>5)throw new Error('invalid retry policy');if(attempts>=maxAttempts)return{jobId:clean(job.jobId),action:'dlq',attempts,maxAttempts,reason:clean(job.lastError),autoReplay:false};return{jobId:clean(job.jobId),action:'retry',attempts:attempts+1,maxAttempts,delaySeconds:Math.min(300,15*2**attempts)};}
export function buildManifest(raw,plan,health,recommendation,timeline,draft=null,outcome=null){const data=normalizeCase(raw);if(!plan?.planFingerprint||!health?.healthFingerprint||!recommendation?.recommendationFingerprint)throw new Error('required artifacts missing');const check=verifyTimeline(timeline);if(!check.valid)throw new Error('invalid timeline chain');const manifest={schemaVersion:'1.0',caseId:data.caseId,caseVersion:data.caseVersion,caseFingerprint:caseFingerprint(data),planFingerprint:plan.planFingerprint,healthFingerprint:health.healthFingerprint,recommendationFingerprint:recommendation.recommendationFingerprint,draftFingerprint:draft?.draftFingerprint??null,outcomeFingerprint:outcome?.outcomeFingerprint??null,timelineHeadHash:check.headHash,evidenceBoundary:data.evidenceBoundary,requiresHumanApproval:true,autoSend:false,deliveryAuthorized:false,causalClaimAllowed:false,createdAt:data.asOf};return{...manifest,manifestFingerprint:hash(manifest)};}
