import {createHash} from'node:crypto';
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const round=v=>Number(v.toFixed(4));
const CHANNELS=new Set(['survey','support_ticket','review','social','interview','email']);
const TOPICS={billing:['billing','invoice','charged','charge','refund','price','pricing','پرداخت','صورتحساب','قیمت','بازپرداخت'],reliability:['outage','offline','down','crash','slow','latency','قطعی','کند','خراب'],usability:['confusing','difficult','hard to','navigation','setup','پیچیده','سخت','راه‌اندازی'],support:['support','agent','response','ticket','پشتیبانی','پاسخ','تیکت'],feature_request:['please add','wish','feature','integration','would like','امکان','قابلیت','اضافه کنید'],security:['security','breach','hacked','privacy','امنیت','نقض','حریم خصوصی']};
const POSITIVE=['great','excellent','love','helpful','fast','easy','عالی','خوب','سریع','آسان','راضی'];
const NEGATIVE=['bad','terrible','hate','broken','slow','angry','disappointed','awful','بد','افتضاح','خراب','کند','عصبانی','ناراضی'];
const URGENT=[['security_incident',/\b(?:breach|hacked|data leak|stolen credentials)\b|(?:نشت اطلاعات|هک|سرقت اطلاعات)/i],['safety_risk',/\b(?:unsafe|danger|injury|self[- ]harm)\b|(?:خطر|آسیب|خودکشی)/i],['legal_threat',/\b(?:lawsuit|legal action|regulator)\b|(?:شکایت قضایی|اقدام قانونی|رگولاتور)/i]];

export function scanText(value){const text=clean(value),findings=[];const rules=[['prompt_injection',/ignore (?:all|previous).*instructions|reveal (?:the )?(?:system prompt|secret|token)/i,'block'],['payment_card',/\b(?:\d[ -]*?){13,19}\b/,'block'],['api_secret',/\b(?:api[_ -]?key|password|secret)\s*[:=]\s*\S+/i,'block'],['email',/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i,'redact'],['phone',/(?:\+?\d[\d ()-]{7,}\d)/,'redact']];for(const [code,pattern,action]of rules)if(pattern.test(text))findings.push({code,action});return findings;}
export function redactPII(value){return clean(value).replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[EMAIL_REDACTED]').replace(/(?:\+?\d[\d ()-]{7,}\d)/g,'[PHONE_REDACTED]');}
export function normalizeFeedback(raw){for(const k of ['feedbackId','channel','receivedAt','locale','text'])if(!clean(raw?.[k]))throw new Error(`missing ${k}`);const channel=clean(raw.channel).toLowerCase();if(!CHANNELS.has(channel))throw new Error('unsupported channel');const receivedAt=new Date(raw.receivedAt);if(Number.isNaN(receivedAt.valueOf()))throw new Error('invalid receivedAt');const consent=raw.consent===true;return{feedbackId:clean(raw.feedbackId),channel,receivedAt:receivedAt.toISOString(),locale:clean(raw.locale).toLowerCase(),text:clean(raw.text),customerRef:clean(raw.customerRef),consent,sourceRef:clean(raw.sourceRef),metadata:{...(raw.metadata??{})}};}
export function deduplicateFeedback(rows){if(!Array.isArray(rows)||!rows.length)throw new Error('feedback rows required');const seenIds=new Set(),seenContent=new Set(),accepted=[],duplicates=[];for(const input of rows){const row=normalizeFeedback(input);const contentFingerprint=hash({channel:row.channel,receivedAt:row.receivedAt.slice(0,10),text:row.text.toLowerCase()});if(seenIds.has(row.feedbackId)||seenContent.has(contentFingerprint)){duplicates.push({feedbackId:row.feedbackId,contentFingerprint});continue;}seenIds.add(row.feedbackId);seenContent.add(contentFingerprint);accepted.push({...row,contentFingerprint});}return{accepted,duplicates};}
function matches(text,words){const x=text.toLowerCase();return words.filter(word=>x.includes(word));}
export function classifyFeedback(input){const row=normalizeFeedback(input),safety=scanText(row.text);if(safety.some(x=>x.action==='block'))return{feedbackId:row.feedbackId,status:'blocked',safety,topics:[],sentiment:'unknown',confidence:0,evidence:[]};const topics=Object.entries(TOPICS).map(([topic,words])=>({topic,hits:matches(row.text,words)})).filter(x=>x.hits.length).sort((a,b)=>b.hits.length-a.hits.length||a.topic.localeCompare(b.topic));const positive=matches(row.text,POSITIVE),negative=matches(row.text,NEGATIVE);const sentiment=positive.length===negative.length?'neutral':positive.length>negative.length?'positive':'negative';const signalCount=(topics[0]?.hits.length??0)+positive.length+negative.length;return{feedbackId:row.feedbackId,status:topics.length?'classified':'needs_review',safety,topics:topics.map(x=>x.topic),sentiment,confidence:round(Math.min(.98,.45+signalCount*.09)),evidence:[...new Set([...(topics[0]?.hits??[]),...positive,...negative])].sort()};}
export function detectUrgency(input){const row=normalizeFeedback(input),matches=URGENT.filter(([,p])=>p.test(row.text)).map(([code])=>code);const severe=/\b(?:immediately|urgent|critical)\b|(?:فوری|بحرانی)/i.test(row.text);return{feedbackId:row.feedbackId,urgent:matches.length>0,codes:matches,priority:matches.length?(severe?'p0':'p1'):'normal',action:matches.length?'human_triage_required':'no_escalation',autoContactCustomer:false};}
export function analyzeBatch(inputs,options={}){const{accepted,duplicates}=deduplicateFeedback(inputs);const records=accepted.map(row=>{const classification=classifyFeedback(row),urgency=detectUrgency(row),redactedText=redactPII(row.text);return{...row,text:undefined,customerRef:undefined,redactedText,classification,urgency,usableForAggregate:row.consent&&classification.status!=='blocked'};});const aggregate=aggregateInsights(records,{minimumGroupSize:options.minimumGroupSize??3,minimumSourceChannels:options.minimumSourceChannels??2});return{records,duplicates,aggregate,evidenceBoundary:'simulated',runFingerprint:hash({records:records.map(r=>({id:r.feedbackId,class:r.classification,urgency:r.urgency})),options})};}
export function aggregateInsights(records,options={}){const minimumGroupSize=Number(options.minimumGroupSize??3),minimumSourceChannels=Number(options.minimumSourceChannels??2);if(minimumGroupSize<2)throw new Error('minimumGroupSize must be at least 2');const usable=records.filter(r=>r.usableForAggregate),byTopic=new Map();for(const r of usable)for(const topic of r.classification.topics){if(!byTopic.has(topic))byTopic.set(topic,[]);byTopic.get(topic).push(r);}const insights=[];for(const[topic,rows]of byTopic){const channels=[...new Set(rows.map(r=>r.channel))].sort(),sourceIds=rows.map(r=>r.feedbackId).sort(),negative=rows.filter(r=>r.classification.sentiment==='negative').length,eligible=rows.length>=minimumGroupSize&&channels.length>=minimumSourceChannels;insights.push({topic,status:eligible?'review_ready':'insufficient_evidence',sampleSize:rows.length,sourceChannels:channels,negativeRate:round(rows.length?negative/rows.length:0),sourceFeedbackIds:sourceIds,evidenceQuotes:eligible?rows.slice(0,3).map(r=>({feedbackId:r.feedbackId,quote:r.redactedText.slice(0,180)})):[],claim:eligible?`${topic} appeared in ${rows.length} consented feedback items across ${channels.length} channels.`:null,requiresReviewer:true});}return{minimumGroupSize,minimumSourceChannels,consentedSampleSize:usable.length,excludedCount:records.length-usable.length,insights:[...insights].sort((a,b)=>b.sampleSize-a.sampleSize||a.topic.localeCompare(b.topic))};}
export function comparePeriods(previous,current){const count=rows=>{const m=new Map();for(const r of rows.filter(x=>x.usableForAggregate))for(const t of r.classification.topics)m.set(t,(m.get(t)??0)+1);return m;};const a=count(previous),b=count(current),topics=[...new Set([...a.keys(),...b.keys()])].sort();return topics.map(topic=>{const before=a.get(topic)??0,after=b.get(topic)??0;return{topic,before,after,delta:after-before,direction:after>before?'up':after<before?'down':'flat'};});}
export function recordInsightReview(insight,review){for(const k of ['reviewerId','reviewerRole','decision','rationale'])if(!clean(review?.[k]))throw new Error(`missing review ${k}`);if(!['voc_analyst','customer_experience_lead'].includes(review.reviewerRole))throw new Error('unauthorized reviewer');if(!['approve','reject','request_changes'].includes(review.decision))throw new Error('invalid decision');if(insight.status!=='review_ready'&&review.decision==='approve')throw new Error('insufficient evidence cannot be approved');return{topic:insight.topic,decision:review.decision,reviewerId:clean(review.reviewerId),reviewerRole:review.reviewerRole,rationale:clean(review.rationale),reviewedAt:clean(review.reviewedAt||'2026-01-01T00:00:00Z'),auditFingerprint:hash({insight,review})};}
export function buildExportManifest(report){if(!report?.runFingerprint)throw new Error('verified report required');return{schemaVersion:'1.0',runFingerprint:report.runFingerprint,recordCount:report.records.length,duplicateCount:report.duplicates.length,insightCount:report.aggregate.insights.length,evidenceBoundary:report.evidenceBoundary,containsRawPII:false,createdAt:'2026-01-01T00:00:00Z',manifestFingerprint:hash({runFingerprint:report.runFingerprint,recordCount:report.records.length,duplicateCount:report.duplicates.length})};}
