import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{normalizeSource,sourceKey,jobKey,normalizeMemory,normalizeGlossary,translateSegments,buildSrt,createLocalizedPackage,qualityGate,transitionPackage,buildExportManifest,classifyDelivery,computeKpis}from'../src/core.mjs';
const load=async p=>JSON.parse(await readFile(new URL(p,import.meta.url)));const source=await load('../examples/valid-source-content.json'),memory=await load('../locales/translation-memory.json'),glossary=await load('../locales/glossary.json'),profiles=await load('../locales/profiles.json');
test('normalizes valid source',()=>assert.equal(normalizeSource(source).schemaVersion,'1.0'));
test('rejects missing fields',()=>assert.throws(()=>normalizeSource({...source,title:''}),/missing title/));
test('rejects unsupported source locale',()=>assert.throws(()=>normalizeSource({...source,sourceLocale:'de-DE'}),/unsupported source locale/));
test('rejects source as target',()=>assert.throws(()=>normalizeSource({...source,targetLocales:['en-US']}),/invalid target locales/));
test('rejects duplicate target locales',()=>assert.throws(()=>normalizeSource({...source,targetLocales:['fa-IR','fa-IR']}),/invalid target locales/));
test('rejects unsupported format',()=>assert.throws(()=>normalizeSource({...source,formats:['podcast']}),/invalid formats/));
test('rejects duplicate format',()=>assert.throws(()=>normalizeSource({...source,formats:['email','email']}),/invalid formats/));
test('rejects duplicate segment identity',()=>assert.throws(()=>normalizeSource({...source,segments:[source.segments[0],source.segments[0]]}),/duplicate segment/));
test('requires timing pair',()=>assert.throws(()=>normalizeSource({...source,segments:[{...source.segments[0],endMs:undefined}]}),/timing pair/));
test('rejects inverted timing',()=>assert.throws(()=>normalizeSource({...source,segments:[{...source.segments[0],startMs:3000,endMs:1000}]}),/invalid subtitle timing/));
test('source key is stable and scoped',()=>{const a=normalizeSource(source);assert.equal(sourceKey(a),sourceKey(a));assert.notEqual(sourceKey(a),sourceKey({...a,sourceLocale:'fa-IR'}))});
test('job key is locale and version scoped',()=>{const a=normalizeSource(source);assert.notEqual(jobKey(a,'fa-IR',1),jobKey(a,'es-ES',1));assert.notEqual(jobKey(a,'fa-IR',1),jobKey(a,'fa-IR',2))});
test('normalizes translation memory',()=>assert.equal(normalizeMemory(memory).entries.length,6));
test('rejects invalid memory',()=>assert.throws(()=>normalizeMemory({version:0,entries:[]}),/invalid translation memory/));
test('normalizes glossary',()=>assert.equal(normalizeGlossary(glossary).version,1));
test('translates Persian from approved exact memory',()=>assert.equal(translateSegments(source,'fa-IR',memory)[0].text,'اتوماسیون قابل اعتماد به شواهد نیاز دارد.'));
test('translates Spanish from approved exact memory',()=>assert.match(translateSegments(source,'es-ES',memory)[0].text,/automatización/));
test('missing memory fails closed with marker',async()=>{const x=await load('../examples/missing-memory-source.json');assert.match(translateSegments(x,'fa-IR',memory)[0].text,/NEEDS_TRANSLATION/)});
test('unapproved memory is ignored',()=>{const m={...memory,entries:memory.entries.map(x=>({...x,approved:false}))};assert.match(translateSegments(source,'fa-IR',m)[0].text,/NEEDS_TRANSLATION/)});
test('SRT is deterministic and timed',()=>{const x=buildSrt(translateSegments(source,'fa-IR',memory));assert.match(x,/00:00:00,000 --> 00:00:02,800/);assert.match(x,/\n2\n/) });
test('creates five Persian formats',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles);assert.equal(Object.keys(p.variants).length,5);assert.equal(p.variants.email.dir,'rtl')});
test('creates five Spanish formats',()=>{const p=createLocalizedPackage(source,'es-ES',memory,glossary,profiles);assert.equal(Object.keys(p.variants).length,5);assert.equal(p.variants.email.dir,'ltr')});
test('package production is deterministic',()=>assert.equal(createLocalizedPackage(source,'fa-IR',memory,glossary,profiles).fingerprint,createLocalizedPackage(source,'fa-IR',memory,glossary,profiles).fingerprint));
test('package version changes fingerprint',()=>assert.notEqual(createLocalizedPackage(source,'fa-IR',memory,glossary,profiles,1).fingerprint,createLocalizedPackage(source,'fa-IR',memory,glossary,profiles,2).fingerprint));
test('rejects unrequested locale',()=>assert.throws(()=>createLocalizedPackage(source,'en-US',memory,glossary,profiles),/target locale not requested/));
test('requires locale profile',()=>assert.throws(()=>createLocalizedPackage(source,'fa-IR',memory,glossary,{}),/locale profile missing/));
test('valid Persian package proceeds to review',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles),q=qualityGate(p,source,glossary,profiles);assert.equal(q.passed,true);assert.equal(q.decision,'needs_review')});
test('missing translation blocks QA',async()=>{const x=await load('../examples/missing-memory-source.json'),p=createLocalizedPackage(x,'fa-IR',memory,glossary,profiles),q=qualityGate(p,x,glossary,profiles);assert.ok(q.findings.some(f=>f.code==='translation_missing'));assert.equal(q.decision,'qa_failed')});
test('prompt injection blocks QA',async()=>{const x=await load('../examples/injection-source.json'),p=createLocalizedPackage(x,'fa-IR',memory,glossary,profiles),q=qualityGate(p,x,glossary,profiles);assert.ok(q.findings.some(f=>f.code==='prompt_injection_content'))});
test('PII blocks QA',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles);p.segments[0].text+=' test@example.com';assert.ok(qualityGate(p,source,glossary,profiles).findings.some(f=>f.code==='pii_detected'))});
test('missing format blocks QA',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles);delete p.variants.email;assert.ok(qualityGate(p,source,glossary,profiles).findings.some(f=>f.code==='missing_format'))});
test('direction mismatch blocks QA',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles);p.variants.email.dir='ltr';assert.ok(qualityGate(p,source,glossary,profiles).findings.some(f=>f.code==='direction_metadata_mismatch'))});
test('subtitle overlap blocks QA',()=>{const x={...source,segments:source.segments.map((s,i)=>i===1?{...s,startMs:2000}:s)},p=createLocalizedPackage(x,'fa-IR',memory,glossary,profiles);assert.ok(qualityGate(p,x,glossary,profiles).findings.some(f=>f.code==='subtitle_overlap'))});
test('missing alt text blocks QA',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles);p.variants.carousel_copy.slides[0].altText='';assert.ok(qualityGate(p,source,glossary,profiles).findings.some(f=>f.code==='missing_alt_text'))});
test('forbidden localized term blocks QA',()=>{const p=createLocalizedPackage(source,'fa-IR',memory,glossary,profiles);p.variants.email.body+=' درآمد تضمینی';assert.ok(qualityGate(p,source,glossary,profiles).findings.some(f=>f.code==='forbidden_localized_term'))});
test('invalid transition is rejected',()=>assert.throws(()=>transitionPackage(createLocalizedPackage(source,'fa-IR',memory,glossary,profiles),'released','a','language_reviewer'),/invalid transition/));
test('approval matrix blocks missing roles',()=>{const p={...createLocalizedPackage(source,'fa-IR',memory,glossary,profiles),status:'needs_review'};assert.throws(()=>transitionPackage(p,'approved','a','language_reviewer',['language_reviewer','brand_reviewer'],[]),/missing approvals/)});
test('approval matrix accepts all roles',()=>{const p={...createLocalizedPackage(source,'fa-IR',memory,glossary,profiles),status:'needs_review'};assert.equal(transitionPackage(p,'approved','b','brand_reviewer',['language_reviewer','brand_reviewer'],[{role:'language_reviewer',status:'approved'}]).status,'approved')});
test('export requires approved package',()=>assert.throws(()=>buildExportManifest(createLocalizedPackage(source,'fa-IR',memory,glossary,profiles),[]),/approved package/));
test('export hashes every localized file',()=>{const p={...createLocalizedPackage(source,'fa-IR',memory,glossary,profiles),status:'approved'},m=buildExportManifest(p,[]);assert.equal(m.files.length,5);assert.ok(m.files.every(x=>x.sha256.length===64&&x.path.includes('/fa-IR/')))});
test('delivery policy is bounded',()=>{assert.equal(classifyDelivery(202,1),'delivered');assert.equal(classifyDelivery(429,1),'retry');assert.equal(classifyDelivery(500,3),'dlq');assert.equal(classifyDelivery(422,1),'dlq')});
test('KPI counts only verified releases',()=>{const k=computeKpis([{type:'localized_release',evidence:'simulated'},{type:'localized_release',evidence:'provider_verified'}]);assert.equal(k.providerVerifiedReleases,1);assert.equal(k.simulatedBusinessOutcome,false)});
