import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{createFactoryServer}from'../src/server.mjs';const source=JSON.parse(await readFile(new URL('../examples/valid-source-content.json',import.meta.url)));let server,base;test.before(async()=>{server=createFactoryServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`});test.after(()=>new Promise(r=>server.close(r)));const post=async(path,body)=>{const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()}};
test('health exposes free deterministic path',async()=>{const r=await fetch(base+'/health'),x=await r.json();assert.equal(x.paidApis,false);assert.equal(x.formats,5);assert.ok(x.locales.includes('fa-IR'))});
test('source API validates and fingerprints',async()=>{const x=await post('/v1/sources',source);assert.equal(x.status,200);assert.equal(x.body.idempotencyKey.length,64)});
test('localize API creates RTL Persian package',async()=>{const x=await post('/v1/localize',{source,targetLocale:'fa-IR'});assert.equal(x.status,200);assert.equal(x.body.variants.email.dir,'rtl')});
test('QA API requires review for valid localization',async()=>{const p=(await post('/v1/localize',{source,targetLocale:'fa-IR'})).body,x=await post('/v1/qa',{package:p,source});assert.equal(x.body.decision,'needs_review')});
test('export API rejects unapproved package',async()=>{const p=(await post('/v1/localize',{source,targetLocale:'fa-IR'})).body;assert.equal((await post('/v1/export',{package:p})).status,400)});
test('delivery exposes retriable rate limit',async()=>{const x=await post('/v1/deliver',{simulate:'rate_limit',attempt:1});assert.equal(x.status,429);assert.equal(x.body.outcome,'retry')});
test('metrics are prometheus text',async()=>{const r=await fetch(base+'/metrics');assert.match(await r.text(),/localization_factory_packages_total/)});
test('unknown route is 404',async()=>assert.equal((await fetch(base+'/missing')).status,404));
