import{createHash}from'node:crypto';
const LOCALES=new Set(['en-US','fa-IR','es-ES']);
const FORMATS=new Set(['localized_article','social_post','email','subtitles_srt','carousel_copy']);
const KINDS=new Set(['headline','body','cta','caption']);
const INJECTION=/ignore (?:all |the )?(?:previous|prior) instructions|system prompt|developer message|reveal.*prompt/i;
const PII=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b|(?:\+?\d[\d\s().-]{7,}\d)/i;
const clean=x=>String(x??'').replace(/\s+/g,' ').trim();
const sha=x=>createHash('sha256').update(x).digest('hex');
const uniq=x=>[...new Set(x)];
const pad=n=>String(n).padStart(2,'0');
export function normalizeSource(input){if(!input||typeof input!=='object')throw new Error('source content required');for(const k of['sourceEventId','contentId','version','sourceLocale','title','brandVersion','targetLocales','formats','segments'])if(input[k]===undefined||input[k]==='')throw new Error(`missing ${k}`);if(!LOCALES.has(input.sourceLocale))throw new Error('unsupported source locale');if(!Array.isArray(input.targetLocales)||!input.targetLocales.length||new Set(input.targetLocales).size!==input.targetLocales.length||input.targetLocales.some(x=>!LOCALES.has(x)||x===input.sourceLocale))throw new Error('invalid target locales');if(!Array.isArray(input.formats)||!input.formats.length||new Set(input.formats).size!==input.formats.length||input.formats.some(x=>!FORMATS.has(x)))throw new Error('invalid formats');const version=Number(input.version),brandVersion=Number(input.brandVersion);if(!Number.isInteger(version)||version<1||!Number.isInteger(brandVersion)||brandVersion<1)throw new Error('invalid version');if(!Array.isArray(input.segments)||!input.segments.length||input.segments.length>100)throw new Error('segments required');const segments=input.segments.map((s,i)=>{if(!clean(s.segmentId)||!clean(s.text)||!KINDS.has(s.kind))throw new Error(`invalid segment ${i}`);if((s.startMs===undefined)!==(s.endMs===undefined))throw new Error('subtitle timing pair required');if(s.startMs!==undefined&&(!Number.isInteger(s.startMs)||!Number.isInteger(s.endMs)||s.startMs<0||s.endMs<=s.startMs))throw new Error('invalid subtitle timing');return{segmentId:clean(s.segmentId),text:clean(s.text).slice(0,3000),kind:s.kind,claimId:clean(s.claimId),startMs:s.startMs,endMs:s.endMs}});if(new Set(segments.map(x=>x.segmentId)).size!==segments.length)throw new Error('duplicate segment identity');return{schemaVersion:'1.0',sourceEventId:clean(input.sourceEventId),contentId:clean(input.contentId),version,sourceLocale:input.sourceLocale,title:clean(input.title).slice(0,200),brandVersion,targetLocales:[...input.targetLocales],formats:[...input.formats],segments,evidenceBoundary:input.evidenceBoundary==='source_verified'?'source_verified':'simulated',requestedBy:clean(input.requestedBy||'system')}}
export const sourceKey=s=>sha(`${s.sourceLocale}:${s.sourceEventId}`);
export const jobKey=(s,targetLocale,version=1)=>sha(`${s.contentId}:${s.version}:${targetLocale}:${s.brandVersion}:${version}`);
export function normalizeMemory(input){if(!input||Number(input.version)<1||!Array.isArray(input.entries))throw new Error('invalid translation memory');return{version:Number(input.version),entries:input.entries.map(x=>({...x,source:clean(x.source),target:clean(x.target),approved:x.approved===true}))}}
export function normalizeGlossary(input){if(!input||Number(input.version)<1||!Array.isArray(input.terms))throw new Error('invalid glossary');return{version:Number(input.version),terms:input.terms,doNotTranslate:uniq((input.doNotTranslate??[]).map(clean).filter(Boolean)),forbidden:input.forbidden??{}}}
export function translateSegments(sourceInput,targetLocale,memoryInput){const source=normalizeSource(sourceInput),memory=normalizeMemory(memoryInput);if(!source.targetLocales.includes(targetLocale))throw new Error('target locale not requested');const entries=new Map(memory.entries.filter(x=>x.approved&&x.sourceLocale===source.sourceLocale&&x.targetLocale===targetLocale).map(x=>[x.source,x.target]));return source.segments.map(s=>{const translated=entries.get(s.text);return{...s,sourceText:s.text,text:translated??`[NEEDS_TRANSLATION:${s.segmentId}]`,memoryMatch:translated?'exact':'missing',memoryVersion:memory.version}})}
function formatTime(ms){const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000),x=ms%1000;return`${pad(h)}:${pad(m)}:${pad(s)},${String(x).padStart(3,'0')}`}
export function buildSrt(segments){const timed=segments.filter(x=>x.startMs!==undefined);return timed.map((x,i)=>`${i+1}\n${formatTime(x.startMs)} --> ${formatTime(x.endMs)}\n${x.text}`).join('\n\n')}
export function createLocalizedPackage(sourceInput,targetLocale,memoryInput,glossaryInput,profiles,version=1){const source=normalizeSource(sourceInput),glossary=normalizeGlossary(glossaryInput),profile=profiles[targetLocale];if(!profile)throw new Error('locale profile missing');if(!Number.isInteger(version)||version<1)throw new Error('invalid package version');const segments=translateSegments(source,targetLocale,memoryInput),headline=segments.find(x=>x.kind==='headline')?.text??segments[0].text,body=segments.filter(x=>x.kind==='body').map(x=>x.text).join('\n\n'),cta=segments.find(x=>x.kind==='cta')?.text??'',variants={};if(source.formats.includes('localized_article'))variants.localized_article={title:headline,body,cta,lang:targetLocale,dir:profile.direction};if(source.formats.includes('social_post'))variants.social_post={caption:[headline,body,cta].filter(Boolean).join('\n'),lang:targetLocale,dir:profile.direction};if(source.formats.includes('email'))variants.email={subject:headline.slice(0,60),body:[body,cta].filter(Boolean).join('\n\n'),lang:targetLocale,dir:profile.direction};if(source.formats.includes('subtitles_srt'))variants.subtitles_srt={content:buildSrt(segments),lang:targetLocale,dir:profile.direction};if(source.formats.includes('carousel_copy'))variants.carousel_copy={slides:segments.map((x,i)=>({number:i+1,body:x.text,altText:`${profile.language} slide ${i+1}`})),lang:targetLocale,dir:profile.direction};const base={packageId:jobKey(source,targetLocale,version),version,status:'localized',sourceIdentity:sourceKey(source),contentId:source.contentId,sourceVersion:source.version,sourceLocale:source.sourceLocale,targetLocale,brandVersion:source.brandVersion,memoryVersion:normalizeMemory(memoryInput).version,glossaryVersion:glossary.version,segments,formats:source.formats,variants,evidenceBoundary:source.evidenceBoundary,generatedBy:'deterministic-approved-memory-v1'};return{...base,fingerprint:sha(JSON.stringify(base))}}
export function qualityGate(pkg,sourceInput,glossaryInput,profiles){const source=normalizeSource(sourceInput),glossary=normalizeGlossary(glossaryInput),profile=profiles[pkg.targetLocale],findings=[];if(!profile)findings.push({code:'locale_profile_missing',severity:'error'});for(const s of pkg.segments){if(s.memoryMatch==='missing'||s.text.includes('[NEEDS_TRANSLATION:'))findings.push({code:'translation_missing',severity:'error',segmentId:s.segmentId});if(INJECTION.test(s.sourceText)||INJECTION.test(s.text))findings.push({code:'prompt_injection_content',severity:'error',segmentId:s.segmentId});if(PII.test(s.text))findings.push({code:'pii_detected',severity:'error',segmentId:s.segmentId})}for(const term of glossary.doNotTranslate)for(const [i,s] of source.segments.entries())if(s.text.includes(term)&&!pkg.segments[i]?.text.includes(term))findings.push({code:'do_not_translate_changed',severity:'error',term});for(const term of glossary.forbidden[pkg.targetLocale]??[])if(JSON.stringify(pkg.variants).toLowerCase().includes(term.toLowerCase()))findings.push({code:'forbidden_localized_term',severity:'error',term});for(const format of source.formats)if(!pkg.variants[format])findings.push({code:'missing_format',severity:'error',format});if(profile&&Object.values(pkg.variants).some(v=>v.dir!==profile.direction))findings.push({code:'direction_metadata_mismatch',severity:'error'});const timed=pkg.segments.filter(x=>x.startMs!==undefined);for(let i=1;i<timed.length;i++)if(timed[i].startMs<timed[i-1].endMs)findings.push({code:'subtitle_overlap',severity:'error',segmentId:timed[i].segmentId});for(const s of timed){const seconds=(s.endMs-s.startMs)/1000,cps=[...s.text].length/seconds;if(cps>22)findings.push({code:'subtitle_reading_speed',severity:'review',segmentId:s.segmentId,cps:Number(cps.toFixed(1))})}if(pkg.variants.carousel_copy)for(const slide of pkg.variants.carousel_copy.slides)if(!clean(slide.altText))findings.push({code:'missing_alt_text',severity:'error',slide:slide.number});const requiredRoles=['language_reviewer','brand_reviewer'];if((profile?.sensitivePatterns??[]).some(x=>JSON.stringify(pkg.variants).toLowerCase().includes(x.toLowerCase())))requiredRoles.push('cultural_reviewer');const errors=findings.filter(x=>x.severity==='error').length;return{passed:errors===0,decision:errors?'qa_failed':'needs_review',findings,requiredRoles:uniq(requiredRoles),summary:{errors,reviews:findings.filter(x=>x.severity==='review').length,segmentsChecked:pkg.segments.length,formatsChecked:source.formats.length}}}
const transitions={localized:['qa_failed','needs_review'],qa_failed:['localized','archived'],needs_review:['approved','rejected'],approved:['export_ready','archived'],export_ready:['released'],released:[],rejected:[],archived:[]};
export function transitionPackage(pkg,to,actor,role,requiredRoles=[],approvals=[]){if(!clean(actor))throw new Error('actor required');if(!(transitions[pkg.status]??[]).includes(to))throw new Error(`invalid transition ${pkg.status}->${to}`);if(['approved','rejected'].includes(to)&&!['language_reviewer','brand_reviewer','cultural_reviewer'].includes(role))throw new Error('reviewer role required');if(to==='approved'){const ok=new Set([...approvals,{role,status:'approved'}].filter(x=>x.status==='approved').map(x=>x.role));const missing=requiredRoles.filter(x=>!ok.has(x));if(missing.length)throw new Error(`missing approvals: ${missing.join(',')}`)}return{...pkg,status:to,lastActor:clean(actor),lastRole:clean(role)}}
export function buildExportManifest(pkg,approvals){if(pkg.status!=='approved')throw new Error('approved package required');return{packageId:pkg.packageId,version:pkg.version,targetLocale:pkg.targetLocale,fingerprint:pkg.fingerprint,approvalEvidence:approvals.map(x=>({role:x.role,actor:x.actor,status:x.status})),files:pkg.formats.map(format=>({format,path:`localized/${pkg.contentId}/v${pkg.sourceVersion}/${pkg.targetLocale}/${format}.json`,sha256:sha(JSON.stringify(pkg.variants[format]))})),evidenceBoundary:pkg.evidenceBoundary}}
export function classifyDelivery(status,attempt,max=3){if(status>=200&&status<300)return'delivered';if((status===429||status>=500)&&attempt<max)return'retry';return'dlq'}
export function computeKpis(events){const approved=events.filter(x=>x.type==='package_approved').length,failed=events.filter(x=>x.type==='qa_failed').length,releases=events.filter(x=>x.type==='localized_release'&&x.evidence==='provider_verified').length;return{packagesApproved:approved,qaFailureRate:(approved+failed)?failed/(approved+failed):0,providerVerifiedReleases:releases,simulatedBusinessOutcome:false}}
